import {$,$$,escLua,luaId,download,copyText,toast,uid,encodeProject,readJsonFile,readTextFileSmart,html} from '../assets/common.js';

const IMAGEMAX_TAB=Object.freeze({coordinateW:360,coordinateH:320,clientW:382,clientH:346,insetX:10,insetY:7});
const IM_SCRIPT_HEADER="-- This is IM's script file. Do not remove this comment line.";
const GUI_BUILDER_HEADER='-- ImageMax GUI Builder Pro generated / merged PreScript';
const GUI_METADATA_PREFIX='-- IMAGEMAX_GUI_PROJECT_V1 ';
const state={format:'imagemax-web-gui',version:7,tabs:[{id:uid('tab'),name:'사용자',iniSection:'',controls:[]}],dialogs:[],activeType:'tab',activeId:null,selectedControlId:null,xmlImages:[],xmlMeta:null,imported:{sourceName:'',preludeCode:'',postludeCode:'',encoding:'',parseWarnings:[]},showGrid:false,scale:1};
const scale=()=>Number(state.scale)||1;
state.activeId=state.tabs[0].id;

const el={list:$('#viewList'),canvas:$('#canvas'),title:$('#canvasTitle'),meta:$('#canvasMeta'),inspector:$('#inspector'),behavior:$('#behaviorSection'),badge:$('#selectedBadge'),lua:$('#guiLuaPreview'),del:$('#deleteControl'),modal:$('#viewModal'),validation:$('#validationList'),validationBadge:$('#validationBadge'),runtimeTabs:$('#runtimeTabs'),advanced:$('#advancedLua'),advancedWrap:$('#advancedLuaWrap'),importSummary:$('#importSummary'),behaviorModal:$('#behaviorModal'),stage:$('#runtimeStage'),runtimeWindow:$('#runtimeWindow'),testButton:$('#toggleGuiTest'),testPanel:$('#guiTestPanel'),testLog:$('#guiTestLog')};
let guiTestMode=false,guiTestSequence=0;
const guiTestValues=new Map(),guiTestStates=new Map();

const defaults={
  text:{x:10,y:10,w:-1,h:-1,text:'텍스트',itemVar:''},
  group:{x:10,y:40,w:160,h:80,text:'그룹',itemVar:''},
  button:{x:20,y:60,w:80,h:25,text:'버튼',func:'onButton',itemVar:'',behaviors:[]},
  check:{x:20,y:95,w:-1,h:-1,text:'체크',func:'onCheck',var:'check1',itemVar:'',behaviors:[]},
  radio:{x:20,y:125,w:-1,h:-1,text:'선택',func:'onRadio',var:'radio1',radioGroup:'radioGroup1',itemVar:'',behaviors:[]},
  combo:{x:20,y:160,w:120,h:-1,text:'',func:'onCombo',var:'combo1',items:['선택1','선택2','선택3'],itemVar:'',behaviors:[]},
  edit:{x:20,y:200,w:120,h:-1,text:'편집',func:'',var:'edit1',itemVar:'',behaviors:[]},
  picture:{x:20,y:20,w:120,h:80,path:'image.png',itemVar:''},
  link:{x:20,y:120,w:-1,h:-1,text:'바로가기',url:'https://example.com',itemVar:''}
};

function activeView(){return state.activeType==='tab'?state.tabs.find(x=>x.id===state.activeId):state.dialogs.find(x=>x.id===state.activeId)}
function selectedControl(){return activeView()?.controls.find(c=>c.id===state.selectedControlId)}
function allControls(){return [...state.tabs,...state.dialogs].flatMap(v=>v.controls)}
function clamp(v,min,max){return Math.min(max,Math.max(min,v))}
function isLuaIdent(s=''){return /^[A-Za-z_][A-Za-z0-9_]*$/.test(String(s))}
function uniqueName(base,key='var'){const used=new Set(allControls().map(c=>c[key]).filter(Boolean));let s=base,n=1;while(used.has(s)){n++;s=base.replace(/\d+$/,'')+n}return s}
function uniqueFunc(base='onControl'){return uniqueName(base,'func')}
function viewSize(view=activeView()){return state.activeType==='tab'?{w:IMAGEMAX_TAB.coordinateW,h:IMAGEMAX_TAB.coordinateH}:{w:Number(view?.w||300),h:Number(view?.h||200)}}
function runtimeMetrics(view=activeView()){
  if(state.activeType==='tab')return {w:IMAGEMAX_TAB.clientW,h:IMAGEMAX_TAB.clientH,insetX:IMAGEMAX_TAB.insetX,insetY:IMAGEMAX_TAB.insetY};
  return {w:Number(view?.w||300),h:Number(view?.h||200),insetX:0,insetY:0};
}
let measureCtx=null;
function textWidth(text=''){
  try{if(!measureCtx){const cv=document.createElement('canvas');measureCtx=cv.getContext('2d');measureCtx.font='12px "Malgun Gothic", "맑은 고딕", sans-serif'}return Math.ceil(measureCtx.measureText(String(text)).width)}catch{return String(text).length*8}
}
function actualSize(c){
  const txt=String(c.text||'');
  let w=c.w,h=c.h;
  if(w===-1){
    const tw=textWidth(txt);
    if(c.type==='text'||c.type==='link')w=Math.max(18,tw+4);
    else if(c.type==='check'||c.type==='radio')w=Math.max(20,tw+21);
    else if(c.type==='edit')w=120;
    else if(c.type==='combo')w=120;
    else if(c.type==='button')w=Math.max(44,tw+18);
    else w=70;
  }
  if(h===-1){h=['text','check','radio','link'].includes(c.type)?18:['edit','combo'].includes(c.type)?22:c.type==='button'?23:22}
  return {w:Math.max(8,Number(w)||8),h:Math.max(8,Number(h)||8)};
}
function displaySize(c){
  const sz=actualSize(c);
  return c.type==='group'?{w:sz.w+17,h:sz.h+(c.h===-1?16:14)}:sz;
}
function runtimeOuterSize(view=activeView()){
  const rt=runtimeMetrics(view);
  return state.activeType==='tab'?{w:rt.w,h:rt.h}:{w:rt.w+18,h:rt.h+66};
}
function normalizeState(){
  const incomingVersion=Number(state.version)||0;state.version=7;state.xmlImages=state.xmlImages||[];state.scale=incomingVersion<6?1:(Number(state.scale)||1);state.imported=state.imported||{sourceName:'',preludeCode:'',postludeCode:'',encoding:'',parseWarnings:[]};state.imported.encoding=state.imported.encoding||'';state.imported.parseWarnings=state.imported.parseWarnings||[];state.showGrid=incomingVersion<5?false:state.showGrid!==false;
  for(const v of [...(state.tabs||[]),...(state.dialogs||[])])for(const c of v.controls||[]){c.itemVar=c.itemVar||'';c.behaviors=c.behaviors||[];if(c.type==='radio')c.radioGroup=c.radioGroup||'';}
}

function renderAll(){normalizeState();renderViewList();renderRuntimeTabs();renderCanvas();renderInspector();renderBehaviorSection();renderLua();renderValidation();renderImportSummary();persist()}
function renderViewList(){const rows=[...state.tabs.map(v=>({...v,type:'tab'})),...state.dialogs.map(v=>({...v,type:'dialog'}))];el.list.innerHTML=rows.map(v=>`<button class="btn small ${state.activeId===v.id&&state.activeType===v.type?'soft':''}" data-view-id="${v.id}" data-view-type="${v.type}" style="text-align:left;display:flex;justify-content:space-between"><span>${v.type==='tab'?'탭':'Dialog'} · ${html(v.name)}</span><span class="badge">${v.controls.length}</span></button>`).join('');$$('[data-view-id]',el.list).forEach(b=>b.onclick=()=>{state.activeId=b.dataset.viewId;state.activeType=b.dataset.viewType;state.selectedControlId=null;renderAll()});$$('.dialog-only').forEach(b=>b.disabled=state.activeType!=='dialog')}
function renderRuntimeTabs(){if(state.activeType==='dialog'){el.runtimeTabs.innerHTML=`<button class="runtime-tab active">Dialog · ${html(activeView()?.name||'')}</button>`;return}el.runtimeTabs.innerHTML=`<button class="runtime-tab system-tab" disabled>일반</button>`+state.tabs.map(v=>`<button class="runtime-tab ${v.id===state.activeId?'active':''}" data-runtime-tab="${v.id}">${html(v.name)}</button>`).join('');$$('[data-runtime-tab]',el.runtimeTabs).forEach(b=>b.onclick=()=>{state.activeType='tab';state.activeId=b.dataset.runtimeTab;state.selectedControlId=null;renderAll()})}
function renderCanvas(){
  const view=activeView();if(!view)return;
  const {w:W,h:H}=viewSize(view),rt=runtimeMetrics(view),outer=runtimeOuterSize(view),sc=scale();
  el.canvas.classList.add('imagemax-runtime');
  el.canvas.style.width=`${rt.w}px`;el.canvas.style.height=`${rt.h}px`;
  el.runtimeWindow.style.setProperty('--im-window-width',`${outer.w}px`);
  el.runtimeWindow.style.setProperty('--im-window-height',`${outer.h}px`);
  el.canvas.style.setProperty('--preview-scale','1');
  el.canvas.style.setProperty('--runtime-inset-x',`${rt.insetX}px`);
  el.canvas.style.setProperty('--runtime-inset-y',`${rt.insetY}px`);
  el.canvas.style.setProperty('--grid-step','10px');
  el.canvas.style.setProperty('--grid-x',`${rt.insetX}px`);
  el.canvas.style.setProperty('--grid-y',`${rt.insetY}px`);
  el.canvas.classList.toggle('no-grid',!state.showGrid);
  el.runtimeWindow.classList.toggle('main-preview',state.activeType==='tab');
  el.runtimeWindow.classList.toggle('dialog-preview',state.activeType==='dialog');
  el.runtimeWindow.style.width=`${outer.w}px`;el.runtimeWindow.style.height=`${outer.h}px`;el.runtimeWindow.style.transform=`scale(${sc})`;
  el.stage.style.width=`${outer.w*sc}px`;el.stage.style.height=`${outer.h*sc}px`;
  el.title.textContent=view.name;
  el.meta.textContent=(state.activeType==='tab'?`ImageMax 사용자 영역 실측 ${rt.w} × ${rt.h} · Lua 좌표 ${W} × ${H} · ${Math.round(sc*100)}%`:`ImageMax Dialog ${W} × ${H} · parent_id 방식`)+(guiTestMode?' · 동작 테스트 중':'');
  const boundary=state.activeType==='tab'?`<i class="coord-boundary" style="width:${W}px;height:${H}px"></i>`:'';
  el.canvas.classList.toggle('testing',guiTestMode);el.canvas.innerHTML=boundary+view.controls.map(controlHtml).join('');$$('.ctrl',el.canvas).forEach(guiTestMode?bindTestControl:bindControl);el.del.disabled=guiTestMode||!selectedControl();
}
function controlHtml(c){const cls=`ctrl ${c.type} ${!String(c.text||'').trim()?'empty-label':''} ${c.id===state.selectedControlId?'selected':''}`;const sz=displaySize(c),rt=runtimeMetrics();let inner='';
  const value=guiTestValue(c);
  if(c.type==='check')inner=`<label class="native-test-choice"><input type="checkbox" ${value?'checked':''} ${guiTestMode?'':'tabindex="-1"'}><i class="native-check" aria-hidden="true"></i><span>${html(c.text||'')}</span></label>`;
  else if(c.type==='radio')inner=`<label class="native-test-choice"><input type="radio" name="${html(c.radioGroup||c.var||c.id)}" ${value?'checked':''} ${guiTestMode?'':'tabindex="-1"'}><i class="native-radio" aria-hidden="true"></i><span>${html(c.text||'')}</span></label>`;
  else if(c.type==='combo')inner=`<select class="native-test-select"><option value="-1" ${Number(value)<0?'selected':''}></option>${(c.items||[]).map((x,i)=>`<option value="${i}" ${i===Number(value)?'selected':''}>${html(x)}</option>`).join('')}</select><span class="combo-arrow" aria-hidden="true">▼</span>`;
  else if(c.type==='edit')inner=`<input class="native-test-edit" value="${html(value)}">`;
  else if(c.type==='group')inner=`<span class="group-title">${html(c.text||'')}</span>`;
  else if(c.type==='picture')inner=`<span>🖼 ${html(c.path||'image.png')}</span>`;
  else if(c.type==='link')inner=`<span class="link-value">${html(c.text||'링크')}</span>`;
  else if(c.type==='button')inner=`<button class="native-test-button" type="button">${html(c.text||'버튼')}</button>`;
  else inner=`<span>${html(c.text||c.type)}</span>`;
  const nativeOffset=c.type==='group'?'transform:translate(-8px,-5px);':'';
  return `<div class="${cls}" data-id="${c.id}" title="${html(c.itemVar||c.var||c.func||c.type)}" style="left:${c.x+rt.insetX}px;top:${c.y+rt.insetY}px;width:${sz.w}px;height:${sz.h}px;${nativeOffset}z-index:${c.z||1}">${inner}<i class="handle"></i></div>`}
function guiTestValue(c){if(guiTestValues.has(c.id))return guiTestValues.get(c.id);const value=c.type==='edit'?c.text||'':c.type==='combo'?-1:0;guiTestValues.set(c.id,value);return value}
function resetGuiTestSession(clearLog=true){guiTestValues.clear();guiTestStates.clear();if(clearLog){el.testLog.innerHTML='';guiTestSequence=0}}
function guiTestLog(kind,message){guiTestSequence++;const row=document.createElement('div');row.className=`gui-test-row ${kind}`;row.innerHTML=`<span>${String(guiTestSequence).padStart(2,'0')}</span><b>${html(kind)}</b><code>${html(message)}</code>`;el.testLog.append(row);el.testLog.scrollTop=el.testLog.scrollHeight}
function luaComparable(value){const s=String(value??'').trim();if(/^[-+]?\d+(\.\d+)?$/.test(s))return Number(s);if(s==='true')return true;if(s==='false')return false;return s}
function behaviorPass(value,b){if(b.condition==='always')return true;const a=luaComparable(value),z=luaComparable(b.compare);return {eq:a===z,ne:a!==z,gt:a>z,ge:a>=z,lt:a<z,le:a<=z}[b.condition]??false}
function testControlByItemVar(itemVar){return allControls().find(x=>x.itemVar===itemVar)}
function controlView(c){return [...state.tabs,...state.dialogs].find(view=>view.controls?.some(x=>x.id===c.id))}
function radioGroupMembers(c){const view=controlView(c),key=String(c.radioGroup||'').trim();if(!view||!key)return [c];return view.controls.filter(x=>x.type==='radio'&&String(x.radioGroup||'').trim()===key).sort((a,b)=>(a.z||0)-(b.z||0))}
function radioGroupValue(c){const members=radioGroupMembers(c);return members.findIndex(x=>Number(guiTestValue(x))===1)}
function behaviorSourceValue(c){return c.type==='radio'?radioGroupValue(c):guiTestValue(c)}
function setGuiTestControlValue(c,value){
  if(c.type==='radio'){const members=radioGroupMembers(c),index=Math.trunc(Number(value));members.forEach((member,i)=>guiTestValues.set(member.id,i===index?1:0));return index}
  const next=c.type==='check'?(Number(value)?1:0):c.type==='combo'?clamp(Math.trunc(Number(value)||0),-1,Math.max(-1,(c.items||[]).length-1)):c.type==='edit'?String(value??''):luaComparable(value);
  guiTestValues.set(c.id,next);return next
}
function applyGuiTestBehavior(source,b){
  const current=behaviorSourceValue(source),condition=behaviorConditionLabel(b,source);
  if(!behaviorPass(current,b)){guiTestLog('조건',`${condition} → 거짓`);return}
  guiTestLog('조건',`${condition} → 참`);
  if(b.action==='imageEnable'){guiTestLog('ImageMax',`EnableImage(${b.enable?'true':'false'}, ${b.targetImage||'대상 없음'})`);return}
  if(['controlEnable','controlShow','controlValue'].includes(b.action)){
    const target=testControlByItemVar(b.targetItemVar);if(!target){guiTestLog('오류',`대상 컨트롤 ${b.targetItemVar||'(없음)'}을 찾지 못했습니다.`);return}
    const status=guiTestStates.get(target.id)||{enabled:true,shown:true};
    if(b.action==='controlEnable'){status.enabled=!!b.enable;guiTestLog('GUI',`${b.targetItemVar} ${status.enabled?'활성':'비활성'}`)}
    else if(b.action==='controlShow'){status.shown=!!b.show;guiTestLog('GUI',`${b.targetItemVar} ${status.shown?'표시':'숨김'}`)}
    else{const changed=setGuiTestControlValue(target,b.value);guiTestLog('GUI',`${b.targetItemVar} = ${JSON.stringify(changed)}`)}
    guiTestStates.set(target.id,status);renderCanvas();return
  }
  if(b.action==='print'||b.action==='message'){guiTestLog(b.action==='print'?'Print':'MessageBox',b.text||'');return}
  guiTestLog('Lua',`${b.raw||'(빈 사용자 Lua)'} · 안전상 실행하지 않음`)
}
function fireGuiTest(c,value){
  let eventValue;
  if(c.type==='radio'){
    const members=radioGroupMembers(c),index=Math.max(0,members.findIndex(x=>x.id===c.id));setGuiTestControlValue(c,index);eventValue=index;
    const owner=members.find(x=>x.var)||members[0];if(owner?.var)guiTestLog('값',`${owner.var} = ${index}`)
  }else{eventValue=setGuiTestControlValue(c,value);if(c.var)guiTestLog('값',`${c.var} = ${JSON.stringify(eventValue)}`)}
  guiTestLog('콜백',c.func?`${c.func}(${c.itemVar||c.id})`:'연결된 콜백 없음');for(const b of c.behaviors||[])applyGuiTestBehavior(c,b);if(c.type==='radio')renderCanvas()
}
function bindTestControl(node){
  const c=activeView()?.controls.find(x=>x.id===node.dataset.id);if(!c)return;const input=node.querySelector('input,select,button');if(!input)return;
  if(c.type==='button')input.onclick=()=>fireGuiTest(c,1);
  else if(c.type==='edit')input.onchange=()=>fireGuiTest(c,input.value);
  else input.onchange=()=>{if(c.type==='radio'&&!input.checked)return;fireGuiTest(c,c.type==='combo'?Number(input.value):input.checked?1:0)};
  const status=guiTestStates.get(c.id)||{enabled:true,shown:true};input.disabled=!status.enabled;node.hidden=!status.shown
}
function bindControl(node){node.querySelectorAll('input,select,button').forEach(x=>{x.disabled=true});node.addEventListener('pointerdown',e=>{e.preventDefault();state.selectedControlId=node.dataset.id;renderInspector();renderBehaviorSection();$$('.ctrl',el.canvas).forEach(n=>n.classList.toggle('selected',n.dataset.id===state.selectedControlId));el.del.disabled=false;if(e.target.classList.contains('handle'))startResize(e,node);else startDrag(e,node)})}
function startDrag(e,node){const c=selectedControl(),sx=e.clientX,sy=e.clientY,ox=c.x,oy=c.y,{w:W,h:H}=viewSize(),rt=runtimeMetrics();node.setPointerCapture(e.pointerId);const move=ev=>{c.x=clamp(Math.round(ox+(ev.clientX-sx)/scale()),0,W);c.y=clamp(Math.round(oy+(ev.clientY-sy)/scale()),0,H);node.style.left=`${c.x+rt.insetX}px`;node.style.top=`${c.y+rt.insetY}px`;updateInspectorXYWH();renderLua();renderValidation()};const up=()=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',up);persist()};node.addEventListener('pointermove',move);node.addEventListener('pointerup',up)}
function startResize(e,node){e.stopPropagation();const c=selectedControl(),sx=e.clientX,sy=e.clientY,sz=actualSize(c),ow=sz.w,oh=sz.h,{w:W,h:H}=viewSize(),rt=runtimeMetrics();node.setPointerCapture(e.pointerId);if(c.w===-1)c.w=ow;if(c.h===-1)c.h=oh;const maxW=state.activeType==='tab'?Math.max(8,rt.w-rt.insetX-c.x):Math.max(8,W-c.x),maxH=state.activeType==='tab'?Math.max(8,rt.h-rt.insetY-c.y):Math.max(8,H-c.y);const move=ev=>{c.w=clamp(Math.round(ow+(ev.clientX-sx)/scale()),8,maxW);c.h=clamp(Math.round(oh+(ev.clientY-sy)/scale()),8,maxH);const ds=displaySize(c);node.style.width=`${ds.w}px`;node.style.height=`${ds.h}px`;updateInspectorXYWH();renderLua();renderValidation()};const up=()=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',up);persist()};node.addEventListener('pointermove',move);node.addEventListener('pointerup',up)}
function updateInspectorXYWH(){const c=selectedControl();if(!c)return;for(const k of ['x','y','w','h']){const x=$(`[data-prop="${k}"]`,el.inspector);if(x)x.value=c[k]}}

function propField(label,key,value,type='text',extra=''){return `<div class="field"><label>${label}</label>${type==='textarea'?`<textarea class="textarea" data-prop="${key}">${html(value??'')}</textarea>`:`<input class="input" data-prop="${key}" type="${type}" value="${html(value??'')}" ${extra}>`}</div>`}
function propSelect(label,key,value,options){return `<div class="field"><label>${label}</label><select class="select" data-prop="${key}">${options.map(o=>`<option value="${html(o.value)}" ${String(o.value)===String(value)?'selected':''}>${html(o.label)}</option>`).join('')}</select></div>`}
function renderInspector(){const view=activeView(),c=selectedControl();if(!view){el.inspector.innerHTML='';return}
  if(!c){el.badge.textContent='화면 설정';el.inspector.innerHTML=`${propField('화면 이름','view:name',view.name)}${propField('INI 섹션','view:iniSection',view.iniSection||'')}${state.activeType==='dialog'?`<div class="rule-grid">${propField('너비','view:w',view.w,'number')}${propField('높이','view:h',view.h,'number')}</div>`:''}<p class="hint">탭은 ImageMax 문서 규격인 360×320 좌표계를 사용합니다. 컨트롤을 선택하면 반환 ID·변수·콜백을 설정할 수 있습니다.</p>`;bindInspector();return}
  el.badge.textContent=c.type;let spec=`<div class="rule-grid">${propField('X','x',c.x,'number')}${propField('Y','y',c.y,'number')}${propField('W (-1=자동)','w',c.w,'number')}${propField('H (-1=자동)','h',c.h,'number')}</div>`;
  if(c.type!=='picture')spec+=propField('표시 텍스트','text',c.text||'');
  spec+=propField('컨트롤 ID 변수 (선택)','itemVar',c.itemVar||'','text','placeholder="예: check_Cri1"');
  if(['button','check','radio','combo','edit'].includes(c.type))spec+=propField('콜백 함수 (비우면 nil/없음)','func',c.func||'');
  if(['check','radio','combo','edit'].includes(c.type))spec+=propField('연결 값 변수','var',c.var||'');
  if(c.type==='radio')spec+=propField('라디오 그룹 이름','radioGroup',c.radioGroup||'');
  if(c.type==='combo')spec+=propField('콤보 항목 (한 줄에 하나)','items',(c.items||[]).join('\n'),'textarea');
  if(c.type==='picture')spec+=propField('이미지 경로','path',c.path||'');
  if(c.type==='link')spec+=propField('URL','url',c.url||'');
  if(c.itemVar)spec+=`<p class="hint"><b>${html(c.itemVar)}</b>에 GUIAdd* 반환 ID가 저장됩니다. GUIItemEnable / GUIItemUpdate / GUIItemShow 대상에 사용할 수 있습니다.</p>`;
  el.inspector.innerHTML=spec;bindInspector();
}
function bindInspector(){$$('[data-prop]',el.inspector).forEach(x=>x.addEventListener('input',()=>{const key=x.dataset.prop;if(key.startsWith('view:')){const v=activeView(),k=key.split(':')[1];v[k]=['w','h'].includes(k)?Math.max(20,Number(x.value)||20):x.value}else{const c=selectedControl();if(!c)return;if(['x','y','w','h'].includes(key))c[key]=Number(x.value);else if(key==='items')c.items=x.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);else c[key]=x.value}renderViewList();renderRuntimeTabs();renderCanvas();renderLua();renderValidation();persist()}))}

function renderBehaviorSection(){const c=selectedControl();if(!c||!['button','check','radio','combo','edit'].includes(c.type)){el.behavior.innerHTML='';return}const rows=(c.behaviors||[]).map((b,i)=>`<div class="behavior-row"><div><b>${html(behaviorConditionLabel(b))}</b><div class="hint">${html(behaviorActionLabel(b))}</div></div><button class="btn danger small" data-del-behavior="${i}">삭제</button></div>`).join('');el.behavior.innerHTML=`<div class="row" style="justify-content:space-between"><div class="section-label" style="margin:0">노코드 동작 규칙</div><button id="addBehavior" class="btn small soft">+ 규칙</button></div><p class="hint">체크/콤보 값에 따라 ImageMax 이미지를 켜거나 다른 GUI 컨트롤을 활성화하는 코드를 자동 생성합니다.</p><div class="stack">${rows||'<div class="hint">아직 규칙이 없습니다. 기존 PreScript에서 가져온 함수는 아래 고급 Lua 영역에 그대로 보존됩니다.</div>'}</div>`;$('#addBehavior').onclick=openBehaviorModal;$$('[data-del-behavior]',el.behavior).forEach(b=>b.onclick=()=>{c.behaviors.splice(Number(b.dataset.delBehavior),1);renderAll()})}
function behaviorConditionLabel(b,source=selectedControl()){if(b.condition==='always')return '항상';const op={eq:'==',ne:'~=',gt:'>',ge:'>=',lt:'<',le:'<='}[b.condition]||'==';const variable=source?.type==='radio'?(radioGroupMembers(source).find(x=>x.var)?.var||source.var):(source?.var);return `${variable||'현재값'} ${op} ${b.compare}`}
function behaviorActionLabel(b){if(b.action==='imageEnable')return `${b.enable?'활성':'비활성'} 이미지: ${b.targetImage||'(선택 안 됨)'}`;if(b.action==='controlEnable')return `${b.enable?'활성':'비활성'} GUI: ${b.targetItemVar||'(선택 안 됨)'}`;if(b.action==='controlValue')return `GUI 값 변경: ${b.targetItemVar||'?'} = ${b.value??''}`;if(b.action==='controlShow')return `${b.show?'표시':'숨김'} GUI: ${b.targetItemVar||'?'}`;if(b.action==='print')return `로그: ${b.text||''}`;if(b.action==='message')return `MessageBox: ${b.text||''}`;return `Lua: ${b.raw||''}`}

let pendingBehavior=null;
function openBehaviorModal(){const c=selectedControl();if(!c)return;pendingBehavior={condition:c.type==='button'?'always':'eq',compare:'1',action:'imageEnable',targetImage:state.xmlImages[0]||'',enable:true,targetItemVar:'',value:'1',show:true,text:'',raw:''};$('#behaviorCondition').value=pendingBehavior.condition;$('#behaviorCompare').value='1';$('#behaviorAction').value='imageEnable';renderBehaviorModal();el.behaviorModal.classList.add('open')}
function renderBehaviorModal(){const cond=$('#behaviorCondition').value;$('#behaviorCompareField').style.display=cond==='always'?'none':'block';const action=$('#behaviorAction').value;const targets=allControls().filter(x=>x.itemVar).map(x=>x.itemVar);let h='';if(action==='imageEnable'){const opts=state.xmlImages.length?state.xmlImages.map(n=>`<option value="${html(n)}">${html(n)}</option>`).join(''):'<option value="">XML을 먼저 불러오거나 직접 입력</option>';h=`<div class="field"><label>이미지</label><select id="behaviorTargetImage" class="select">${opts}</select></div><div class="field"><label>상태</label><select id="behaviorBool" class="select"><option value="true">활성</option><option value="false">비활성</option></select></div><div class="field"><label>이미지 직접 입력 (선택)</label><input id="behaviorTargetImageManual" class="input"></div>`}
else if(action==='controlEnable'||action==='controlShow'||action==='controlValue'){h=`<div class="field"><label>대상 컨트롤 ID 변수</label><select id="behaviorTargetControl" class="select"><option value="">선택</option>${targets.map(n=>`<option value="${html(n)}">${html(n)}</option>`).join('')}</select></div>${action==='controlValue'?'<div class="field"><label>설정 값</label><input id="behaviorValue" class="input" value="1"></div>':`<div class="field"><label>상태</label><select id="behaviorBool" class="select"><option value="true">${action==='controlShow'?'표시':'활성'}</option><option value="false">${action==='controlShow'?'숨김':'비활성'}</option></select></div>`}`}
else if(action==='print'||action==='message')h=`<div class="field"><label>문구</label><input id="behaviorText" class="input" placeholder="실행 시 표시할 문구"></div>${action==='message'?'<p class="hint warn-text">MessageBox는 ImageMax 쓰레드를 멈추므로 GUI 콜백에서만 사용하는 것이 권장됩니다.</p>':''}`;
else h=`<div class="field"><label>Lua 한 줄</label><textarea id="behaviorRaw" class="textarea mono" placeholder="예: OpenScript(\'재실행\')"></textarea></div>`;$('#behaviorDynamic').innerHTML=h}
$('#behaviorCondition').onchange=renderBehaviorModal;$('#behaviorAction').onchange=renderBehaviorModal;$('#cancelBehavior').onclick=()=>el.behaviorModal.classList.remove('open');$('#confirmBehavior').onclick=()=>{const c=selectedControl();if(!c)return;const action=$('#behaviorAction').value,b={id:uid('beh'),condition:$('#behaviorCondition').value,compare:$('#behaviorCompare').value,action};if(action==='imageEnable'){b.targetImage=$('#behaviorTargetImageManual')?.value.trim()||$('#behaviorTargetImage')?.value||'';b.enable=$('#behaviorBool').value==='true'}else if(action==='controlEnable'){b.targetItemVar=$('#behaviorTargetControl').value;b.enable=$('#behaviorBool').value==='true'}else if(action==='controlShow'){b.targetItemVar=$('#behaviorTargetControl').value;b.show=$('#behaviorBool').value==='true'}else if(action==='controlValue'){b.targetItemVar=$('#behaviorTargetControl').value;b.value=$('#behaviorValue').value}else if(action==='print'||action==='message')b.text=$('#behaviorText').value;else b.raw=$('#behaviorRaw').value;c.behaviors=c.behaviors||[];c.behaviors.push(b);if(!c.func)c.func=uniqueFunc(`on_${c.type}`);el.behaviorModal.classList.remove('open');renderAll()};

function addControl(type){const view=activeView();if(!view)return;if((type==='picture'||type==='link')&&state.activeType!=='dialog'){toast('Picture/Link는 Dialog에서 추가하세요.');return}const d=structuredClone(defaults[type]),id=uid(type);if(d.var)d.var=uniqueName(d.var,'var');if(d.func)d.func=uniqueFunc(d.func);view.controls.push({id,type,z:view.controls.length+1,...d});state.selectedControlId=id;renderAll()}
$$('.tool').forEach(b=>b.onclick=()=>addControl(b.dataset.type));el.del.onclick=()=>{const v=activeView();if(!v||!state.selectedControlId)return;v.controls=v.controls.filter(c=>c.id!==state.selectedControlId);state.selectedControlId=null;renderAll()};$('#toggleGrid').onclick=()=>{state.showGrid=!state.showGrid;renderCanvas();persist()};

let modalType='tab';function openViewModal(type){modalType=type;$('#viewModalTitle').textContent=type==='tab'?'새 탭 추가':'새 Dialog 추가';$('#viewName').value=type==='tab'?`탭${state.tabs.length+1}`:`Dialog${state.dialogs.length+1}`;$('#viewIni').value='';$('#dialogSizeFields').style.display=type==='dialog'?'flex':'none';el.modal.classList.add('open');$('#viewName').focus()}
$('#addTab').onclick=()=>openViewModal('tab');$('#addDialog').onclick=()=>openViewModal('dialog');$('#cancelView').onclick=()=>el.modal.classList.remove('open');$('#confirmView').onclick=()=>{const name=$('#viewName').value.trim();if(!name){toast('이름을 입력하세요.');return}const obj={id:uid(modalType),name,iniSection:$('#viewIni').value.trim(),controls:[]};if(modalType==='dialog'){obj.w=Math.max(20,Number($('#dialogW').value)||300);obj.h=Math.max(20,Number($('#dialogH').value)||200);state.dialogs.push(obj)}else state.tabs.push(obj);state.activeType=modalType;state.activeId=obj.id;state.selectedControlId=null;el.modal.classList.remove('open');renderAll()};

function luaVal(v){const s=String(v??'').trim();if(s==='')return "''";if(/^[-+]?\d+(\.\d+)?$/.test(s))return s;if(s==='true'||s==='false'||s==='nil')return s;return escLua(s)}
function callbackDefined(name){if(!name)return false;const re=new RegExp(`\\bfunction\\s+${name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s*\\(`);return re.test(state.imported?.preludeCode||'')}
function callbackNameCounts(){const counts=new Map();for(const c of allControls())if(c.func)counts.set(c.func,(counts.get(c.func)||0)+1);return counts}
function generatedCallbackName(c,counts=callbackNameCounts()){const base=luaId(c.func||`on_${c.type}_${c.id}`),hasRules=(c.behaviors||[]).length>0,needsWrapper=hasRules&&c.func&&((counts.get(c.func)||0)>1||callbackDefined(c.func));return needsWrapper?`${base}__imx_${luaId(c.itemVar||c.id)}`:base}
function controlValueVariable(c){return c?.type==='radio'?(radioGroupMembers(c).find(x=>x.var)?.var||c.var||''):(c?.var||'')}
function behaviorLua(c,b,indent='    '){let action='';if(b.action==='imageEnable')action=`EnableImage(${b.enable?'true':'false'}, ${escLua(b.targetImage||'이미지명')})`;else if(b.action==='controlEnable')action=`GUIItemEnable(${luaId(b.targetItemVar||'control_id')}, ${b.enable?'true':'false'})`;else if(b.action==='controlShow')action=`GUIItemShow(${luaId(b.targetItemVar||'control_id')}, ${b.show?'true':'false'})`;else if(b.action==='controlValue'){const target=allControls().find(x=>x.itemVar===b.targetItemVar),val=luaVal(b.value),targetVar=controlValueVariable(target);action=targetVar?`${luaId(targetVar)} = ${val}\n${indent}GUIItemUpdate(${luaId(b.targetItemVar||'control_id')}, ${luaId(targetVar)})`:`GUIItemUpdate(${luaId(b.targetItemVar||'control_id')}, ${val})`}else if(b.action==='print')action=`Print(${escLua(b.text||'')})`;else if(b.action==='message')action=`MessageBox(${escLua(b.text||'')})`;else action=b.raw||'-- TODO';const sourceVar=controlValueVariable(c);if(b.condition==='always'||!sourceVar)return indent+action.replace(/\n/g,'\n'+indent);const op={eq:'==',ne:'~=',gt:'>',ge:'>=',lt:'<',le:'<='}[b.condition]||'==';return `${indent}if ${luaId(sourceVar)} ${op} ${luaVal(b.compare)} then\n${indent}    ${action.replace(/\n/g,'\n'+indent+'    ')}\n${indent}end`}
function generatedHandlers(){const out=[],counts=callbackNameCounts(),emitted=new Set();for(const c of allControls()){const behaviors=c.behaviors||[];if(!c.func&&!behaviors.length)continue;const name=generatedCallbackName(c,counts),base=luaId(c.func||name);if(!behaviors.length){if(!callbackDefined(c.func)&&!emitted.has(base)){out.push(`function ${base}(item_id)\n    -- TODO: ${c.type} 이벤트 동작\nend`);emitted.add(base)}continue}const lines=[];if(name!==base&&callbackDefined(c.func))lines.push(`    ${base}(item_id)`);lines.push(...behaviors.map(b=>behaviorLua(c,b)));if(behaviors.some(b=>b.action==='controlValue'))lines.push('    GUIUpdate()');out.push(`function ${name}(item_id)\n${lines.join('\n')}\nend`);emitted.add(name)}return out.join('\n\n')}
function encodeBase64Utf8(value){const bytes=new TextEncoder().encode(value);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)}
function decodeBase64Utf8(value){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new TextDecoder().decode(bytes)}
function metadataControl(c){return {signature:[c.type,c.x,c.y,c.itemVar||'',c.var||''],id:c.id,func:c.func||'',radioGroup:c.radioGroup||'',behaviors:c.behaviors||[]}}
function encodeGuiMetadata(){return encodeBase64Utf8(JSON.stringify({version:1,tabs:state.tabs.map(view=>view.controls.map(metadataControl)),dialogs:state.dialogs.map(view=>view.controls.map(metadataControl))}))}
function decodeGuiMetadata(text){const line=String(text).split(/\r?\n/).find(value=>value.startsWith(GUI_METADATA_PREFIX));if(!line)return null;const encoded=line.slice(GUI_METADATA_PREFIX.length).trim();if(!encoded||encoded.length>400000||!/^[A-Za-z0-9+/=]+$/.test(encoded))return null;try{const value=JSON.parse(decodeBase64Utf8(encoded));return value?.version===1?value:null}catch{return null}}
function applyGuiMetadata(metadata,tabs,dialogs){if(!metadata)return;for(const key of ['tabs','dialogs']){const views=key==='tabs'?tabs:dialogs;for(const [viewIndex,view] of views.entries())for(const [controlIndex,c] of view.controls.entries()){const saved=metadata[key]?.[viewIndex]?.[controlIndex],signature=[c.type,c.x,c.y,c.itemVar||'',c.var||''];if(!saved||JSON.stringify(saved.signature)!==JSON.stringify(signature))continue;if(/^[A-Za-z0-9_-]{1,120}$/.test(saved.id||''))c.id=saved.id;c.func=String(saved.func||'');c.behaviors=Array.isArray(saved.behaviors)?saved.behaviors.filter(value=>value&&typeof value==='object').slice(0,100):[];if(c.type==='radio')c.radioGroup=String(saved.radioGroup||'')}}}
function cleanImportedCode(text=''){const markers=new Set([IM_SCRIPT_HEADER,GUI_BUILDER_HEADER,'-- ===== 기존 PreScript 함수 / 사용자 로직 (보존) =====','-- ===== 웹 빌더에서 생성한 GUI 이벤트 =====','-- ===== GUI Layout =====','-- ===== 기존 GUI 초기화 / 후처리 (보존) =====','-- [GUIShow 이후] --']);const source=String(text).replace(/^\uFEFF/,'').replace(/-- ===== 웹 빌더에서 생성한 GUI 이벤트 =====[\s\S]*?(?=-- ===== GUI Layout =====|$)/g,'');return source.split(/\r?\n/).filter(line=>{const value=line.trim();return !markers.has(value)&&!value.startsWith(GUI_METADATA_PREFIX)&&!/^-- 탭: /.test(value)}).join('\n').trim()}
function controlLua(c,parent=null,counts=callbackNameCounts()){const a=[c.x,c.y,c.w,c.h],prefix=parent?`${parent}, `:'';let call='';const func=c.func||(c.behaviors||[]).length?escLua(generatedCallbackName(c,counts)):'nil',vr=c.var?escLua(luaId(c.var)):'nil';switch(c.type){case'text':call=`GUIAddText(${prefix}${a.join(', ')}, ${escLua(c.text||'')})`;break;case'group':call=`GUIAddGroup(${prefix}${a.join(', ')}, ${escLua(c.text||'')})`;break;case'button':call=`GUIAddButton(${prefix}${a.join(', ')}, ${escLua(c.text||'')}, ${func})`;break;case'check':call=`GUIAddCheck(${prefix}${a.join(', ')}, ${escLua(c.text||'')}, ${func}, ${vr})`;break;case'radio':call=c.var?`GUIAddRadio(${prefix}${a.join(', ')}, ${escLua(c.text||'')}, ${func}, ${vr})`:`GUIAddRadio(${prefix}${a.join(', ')}, ${escLua(c.text||'')}, ${func})`;break;case'combo':{const t=`combo_${luaId(c.id)}_items`;call=`${t} = {${(c.items||[]).map(escLua).join(', ')}}\n${c.itemVar?luaId(c.itemVar)+' = ':''}GUIAddCombo(${prefix}${a.join(', ')}, ${t}, ${func}, ${vr})`;return call}case'edit':call=`GUIAddEdit(${prefix}${a.join(', ')}, ${escLua(c.text||'')}, ${func}, ${vr})`;break;case'picture':call=`GUIAddPicture(${prefix}${a.join(', ')}, ${escLua(c.path||'image.png')})`;break;case'link':call=`GUIAddLink(${prefix}${a.join(', ')}, ${escLua(c.text||'링크')}, ${escLua(c.url||'')})`;break;default:call='-- unknown control'}return c.itemVar?`${luaId(c.itemVar)} = ${call}`:call}
function generateLua(){const parts=[],prelude=cleanImportedCode(state.imported?.preludeCode),postlude=cleanImportedCode(state.imported?.postludeCode);parts.push(IM_SCRIPT_HEADER);parts.push(GUI_BUILDER_HEADER);parts.push(GUI_METADATA_PREFIX+encodeGuiMetadata());parts.push('');if(prelude)parts.push('-- ===== 기존 PreScript 함수 / 사용자 로직 (보존) =====\n'+prelude+'\n');const gh=generatedHandlers();if(gh)parts.push('-- ===== 웹 빌더에서 생성한 GUI 이벤트 =====\n'+gh+'\n');parts.push('-- ===== GUI Layout =====');for(const tab of state.tabs){parts.push(`-- 탭: ${tab.name}`);parts.push(tab.iniSection?`GUIAddTab(${escLua(tab.name)}, ${escLua(tab.iniSection)})`:`GUIAddTab(${escLua(tab.name)})`);parts.push(`GUISetCurTab(${escLua(tab.name)})`);for(const c of [...tab.controls].sort((a,b)=>(a.z||0)-(b.z||0)))parts.push(controlLua(c));parts.push('')};for(const d of state.dialogs){const did=isLuaIdent(d.sourceVar||'')?d.sourceVar:`dlg_${luaId(d.id)}`;parts.push(`-- Dialog: ${d.name}`);parts.push(`${did} = GUIAddDialog(${escLua(d.name)}, ${escLua(d.iniSection||d.name)}, ${d.w}, ${d.h})`);for(const c of [...d.controls].sort((a,b)=>(a.z||0)-(b.z||0)))parts.push(controlLua(c,did));parts.push(`-- GUIItemShow(${did}, true) -- 필요할 때 Dialog 열기`,'')}parts.push('GUIShow()');if(postlude)parts.push('\n-- ===== 기존 GUI 초기화 / 후처리 (보존) =====\n'+postlude);return parts.join('\n')+'\n'}
function renderLua(){el.lua.textContent=generateLua();el.advanced.value=[state.imported?.preludeCode||'',state.imported?.postludeCode||''].filter(Boolean).join('\n\n-- [GUIShow 이후] --\n\n')}
el.advanced.addEventListener('change',()=>{const marker='\n\n-- [GUIShow 이후] --\n\n';const [a,b='']=el.advanced.value.split(marker);state.imported.preludeCode=a;state.imported.postludeCode=b;renderLua();renderValidation();persist()});

function validate(){const out=[];const tabNames=new Map();for(const t of state.tabs){tabNames.set(t.name,(tabNames.get(t.name)||0)+1)}for(const [n,c] of tabNames)if(c>1)out.push({level:'error',text:`탭 이름 '${n}'이 중복됩니다. GUISetCurTab은 이름을 사용하므로 고유하게 지정하세요.`});const itemVars=new Map(),vars=new Map();for(const v of [...state.tabs,...state.dialogs]){const isTab=state.tabs.some(t=>t.id===v.id),W=isTab?IMAGEMAX_TAB.coordinateW:Number(v.w||300),H=isTab?IMAGEMAX_TAB.coordinateH:Number(v.h||200);for(const c of v.controls){const sz=actualSize(c);if(c.x<0||c.y<0)out.push({level:'error',text:`${v.name}/${c.text||c.type}: X/Y는 0 이상이어야 합니다.`});if(isTab&&(c.x>W||c.y>H))out.push({level:'error',text:`${v.name}/${c.text||c.type}: 탭 좌표 범위 0~${W}, 0~${H}을 벗어났습니다.`});if(c.w!==-1&&c.w<=0)out.push({level:'error',text:`${v.name}/${c.text||c.type}: W는 -1(자동) 또는 양수여야 합니다.`});if(c.h!==-1&&c.h<=0)out.push({level:'error',text:`${v.name}/${c.text||c.type}: H는 -1(자동) 또는 양수여야 합니다.`});const rt=isTab?{w:IMAGEMAX_TAB.clientW-IMAGEMAX_TAB.insetX,h:IMAGEMAX_TAB.clientH-IMAGEMAX_TAB.insetY}:{w:W,h:H};const overflowX=c.w!==-1?c.x+sz.w-rt.w:0,overflowY=c.h!==-1?c.y+sz.h-rt.h:0;if(overflowX>8||overflowY>8)out.push({level:'warn',text:`${v.name}/${c.text||c.type}: 실제 ImageMax 폼 여백까지 포함해도 크게 벗어납니다. (X +${Math.max(0,overflowX)} / Y +${Math.max(0,overflowY)})`});if(c.itemVar){if(!isLuaIdent(c.itemVar))out.push({level:'error',text:`컨트롤 ID 변수 '${c.itemVar}'는 안전한 Lua 식별자가 아닙니다.`});itemVars.set(c.itemVar,(itemVars.get(c.itemVar)||0)+1)}if(c.var){if(!isLuaIdent(c.var))out.push({level:'error',text:`값 변수 '${c.var}'는 안전한 Lua 식별자가 아닙니다.`});vars.set(c.var,(vars.get(c.var)||0)+1)}if(c.func&&!isLuaIdent(c.func))out.push({level:'error',text:`콜백 '${c.func}'는 안전한 Lua 함수명이 아닙니다.`});for(const b of c.behaviors||[]){if(b.action==='imageEnable'&&!b.targetImage)out.push({level:'error',text:`${c.text||c.type}: 이미지 활성 규칙의 대상 이미지가 비어 있습니다.`});if(['controlEnable','controlShow','controlValue'].includes(b.action)&&!b.targetItemVar)out.push({level:'error',text:`${c.text||c.type}: GUI 규칙의 대상 ID 변수가 비어 있습니다.`});if(b.action==='message')out.push({level:'warn',text:`${c.text||c.type}: MessageBox는 ImageMax 쓰레드를 중지하므로 GUI 콜백 안에서만 사용하는 것이 권장됩니다.`})}}}
  for(const [n,c] of itemVars)if(c>1)out.push({level:'error',text:`컨트롤 ID 변수 '${n}'이 ${c}회 사용됩니다. 반환 ID 변수는 고유해야 합니다.`});
  for(const [n,c] of vars)if(c>1){const radios=allControls().filter(x=>x.var===n&&x.type==='radio');if(radios.length!==c)out.push({level:'warn',text:`값 변수 '${n}'이 ${c}개 컨트롤에서 공유됩니다. 의도된 공유인지 확인하세요.`})}
  const groups=new Map();for(const c of allControls().filter(x=>x.type==='radio'&&x.radioGroup)){if(!groups.has(c.radioGroup))groups.set(c.radioGroup,[]);groups.get(c.radioGroup).push(c)}for(const [g,rs] of groups){const withVar=rs.filter(r=>r.var);if(withVar.length>1)out.push({level:'error',text:`라디오 그룹 '${g}'에서 var가 ${withVar.length}개 지정되었습니다. ImageMax 규칙상 첫 번째 라디오에만 var를 지정하세요.`});if(withVar.length===0)out.push({level:'warn',text:`라디오 그룹 '${g}'에 var가 없습니다. 첫 번째 라디오에 그룹 변수를 지정하는 것이 안전합니다.`})}
  if(state.imported?.parseWarnings?.length)out.push({level:'warn',text:`가져온 PreScript에서 GUI 구문 ${state.imported.parseWarnings.length}개를 자동 배치로 해석하지 못했습니다. 동적/여러 줄 GUI 생성은 고급 Lua에서 확인하세요.`});if(state.imported?.preludeCode?.trim())out.push({level:'info',text:'기존 PreScript 함수 로직을 보존 중입니다. 레이아웃 변경 후 ID 변수/함수명이 기존 고급 Lua와 일치하는지 확인하세요.'});return out}
function renderValidation(){const issues=validate(),err=issues.filter(x=>x.level==='error').length,warn=issues.filter(x=>x.level==='warn').length;el.validationBadge.className=`badge ${err?'warn':warn?'warn':'ok'}`;el.validationBadge.textContent=err?`오류 ${err}`:warn?`주의 ${warn}`:'정상';el.validation.innerHTML=issues.length?issues.map(x=>`<div class="validation-item ${x.level}"><span>${x.level==='error'?'오류':x.level==='warn'?'주의':'정보'}</span><p>${html(x.text)}</p></div>`).join(''):'<div class="validation-item ok"><span>정상</span><p>현재 확인 가능한 ImageMax GUI 규칙 위반이 없습니다.</p></div>'}

function stripComment(line){let q=null,esc=false;for(let i=0;i<line.length-1;i++){const ch=line[i],nx=line[i+1];if(esc){esc=false;continue}if(ch==='\\'){esc=true;continue}if(q){if(ch===q)q=null;continue}if(ch==="'"||ch==='"'){q=ch;continue}if(ch==='-'&&nx==='-')return line.slice(0,i)}return line}
function splitTop(s){const out=[];let cur='',q=null,esc=false,p=0,b=0;for(const ch of s){if(esc){cur+=ch;esc=false;continue}if(ch==='\\'){cur+=ch;esc=true;continue}if(q){cur+=ch;if(ch===q)q=null;continue}if(ch==="'"||ch==='"'){q=ch;cur+=ch;continue}if(ch==='(')p++;else if(ch===')')p--;else if(ch==='{')b++;else if(ch==='}')b--;if(ch===','&&p===0&&b===0){out.push(cur.trim());cur='';continue}cur+=ch}if(cur.trim()||s.endsWith(','))out.push(cur.trim());return out}
function numberExpr(expr,env){const toks=expr.match(/\d+(?:\.\d+)?|[A-Za-z_]\w*|[()+\-*/]/g);if(!toks||toks.join('').replace(/\s/g,'')!==expr.replace(/\s/g,''))return NaN;let i=0;function primary(){const t=toks[i++];if(t==='('){const v=add();if(toks[i]===')')i++;return v}if(t==='+'||t==='-'){const v=primary();return t==='-'?-v:v}if(/^\d/.test(t))return Number(t);if(t in env&&typeof env[t]==='number')return env[t];return NaN}function mul(){let v=primary();while(toks[i]==='*'||toks[i]==='/'){const op=toks[i++],r=primary();v=op==='*'?v*r:v/r}return v}function add(){let v=mul();while(toks[i]==='+'||toks[i]==='-'){const op=toks[i++],r=mul();v=op==='+'?v+r:v-r}return v}return add()}
function evalLuaValue(expr,env){expr=expr.trim();if(expr==='nil')return null;if(expr==='true')return true;if(expr==='false')return false;if((expr.startsWith("'")&&expr.endsWith("'"))||(expr.startsWith('"')&&expr.endsWith('"')))return expr.slice(1,-1).replace(/\\n/g,'\n').replace(/\\'/g,"'").replace(/\\"/g,'"').replace(/\\\\/g,'\\');if(expr.startsWith('{')&&expr.endsWith('}'))return splitTop(expr.slice(1,-1)).map(x=>evalLuaValue(x,env));if(expr in env)return env[expr];const n=numberExpr(expr,env);if(!Number.isNaN(n))return n;return expr}
function extractPrelude(lines,firstGui){return lines.slice(0,firstGui).join('\n').trim()}
function importPreScript(text,name='PreScript.lua'){
  const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/),first=lines.findIndex(l=>/\bGUIAddTab\s*\(/.test(stripComment(l)));if(first<0)throw new Error('GUIAddTab()을 찾지 못했습니다. ImageMax GUI가 포함된 PreScript.lua인지 확인하세요.');let lastShow=-1;for(let i=first;i<lines.length;i++)if(/\bGUIShow\s*\(/.test(stripComment(lines[i])))lastShow=i;if(lastShow<0)lastShow=lines.length-1;const env={},tabs=[],dialogs=[],skipped=[];let current=null,currentType='tab';let seq=0;
  // 첫 GUIAddTab 직전에 선언된 gui1 = '탭이름' 같은 최상위 상수를 먼저 읽습니다.
  for(let i=0;i<first;i++){const raw=stripComment(lines[i]);if(/^\s/.test(raw))continue;const a=raw.trim().replace(/^local\s+/,'').match(/^([A-Za-z_]\w*)\s*=\s*(.+)$/);if(a&&!/function|GUIAdd/.test(a[2]))env[a[1]]=evalLuaValue(a[2],env)}
  for(let i=first;i<=lastShow;i++){let line=stripComment(lines[i]).trim();if(!line)continue;
    const callMatch=line.match(/^(?:local\s+)?(?:([A-Za-z_]\w*)\s*=\s*)?(GUIAddTab|GUISetCurTab|GUIAddDialog|GUIAddText|GUIAddGroup|GUIAddButton|GUIAddCheck|GUIAddRadio|GUIAddCombo|GUIAddEdit|GUIAddPicture|GUIAddLink)\s*\((.*)\)\s*;?$/);
    if(callMatch){const lhs=callMatch[1]||'',fn=callMatch[2],args=splitTop(callMatch[3]).map(x=>evalLuaValue(x,env));if(fn==='GUIAddTab'){const name=String(args[0]??`탭${tabs.length+1}`),existing=tabs.find(t=>t.name===name);current=existing||{id:uid('tab'),name,iniSection:args[1]??'',controls:[]};if(!existing)tabs.push(current);currentType='tab';continue}if(fn==='GUISetCurTab'){const name=String(args[0]??'');current=tabs.find(t=>t.name===name)||current;currentType='tab';continue}if(fn==='GUIAddDialog'){const d={id:uid('dialog'),name:String(args[0]??`Dialog${dialogs.length+1}`),iniSection:String(args[1]??args[0]??''),w:Number(args[2])||300,h:Number(args[3])||200,controls:[],sourceVar:lhs||''};dialogs.push(d);if(lhs)env[lhs]={__dialogRef:d.id};continue}
      let parentView=null,off=0;if(args[0]&&typeof args[0]==='object'&&args[0].__dialogRef){parentView=dialogs.find(d=>d.id===args[0].__dialogRef)||null;off=1}
      if(!current&&!parentView){current={id:uid('tab'),name:'사용자',iniSection:'',controls:[]};tabs.push(current)}
      const type={GUIAddText:'text',GUIAddGroup:'group',GUIAddButton:'button',GUIAddCheck:'check',GUIAddRadio:'radio',GUIAddCombo:'combo',GUIAddEdit:'edit',GUIAddPicture:'picture',GUIAddLink:'link'}[fn];if(!type)continue;const c={id:uid(type),type,z:++seq,itemVar:lhs||'',behaviors:[],x:Number(args[off])||0,y:Number(args[off+1])||0,w:Number(args[off+2]),h:Number(args[off+3])};if(Number.isNaN(c.w))c.w=-1;if(Number.isNaN(c.h))c.h=-1;
      if(type==='text'||type==='group'){c.text=String(args[off+4]??'')}else if(type==='button'){c.text=String(args[off+4]??'');c.func=args[off+5]==null?'':String(args[off+5])}else if(type==='check'||type==='radio'){c.text=String(args[off+4]??'');c.func=args[off+5]==null?'':String(args[off+5]);c.var=args[off+6]==null?'':String(args[off+6]);if(type==='radio')c.radioGroup=''}else if(type==='combo'){c.items=Array.isArray(args[off+4])?args[off+4]:[];c.text='';c.func=args[off+5]==null?'':String(args[off+5]);c.var=args[off+6]==null?'':String(args[off+6])}else if(type==='edit'){c.text=String(args[off+4]??'');c.func=args[off+5]==null?'':String(args[off+5]);c.var=args[off+6]==null?'':String(args[off+6])}else if(type==='picture')c.path=String(args[off+4]??'');else if(type==='link'){c.text=String(args[off+4]??'');c.url=String(args[off+5]??'')};(parentView||current).controls.push(c);continue}
    if(/\b(?:GUIAdd(?:Tab|Dialog|Text|Group|Button|Check|Radio|Combo|Edit|Picture|Link)|GUISetCurTab)\s*\(/.test(line))skipped.push({line:i+1,text:line.slice(0,160)});
    const asn=line.replace(/^local\s+/,'').match(/^([A-Za-z_]\w*(?:\s*,\s*[A-Za-z_]\w*)*)\s*=\s*(.+)$/);if(asn&&!/GUIAdd/.test(asn[2])){const names=asn[1].split(',').map(s=>s.trim()),vals=splitTop(asn[2]).map(x=>evalLuaValue(x,env));names.forEach((n,j)=>{env[n]=vals[j]});}
  }
  if(!tabs.length)throw new Error('탭 레이아웃을 해석하지 못했습니다.');for(const view of [...tabs,...dialogs]){let group='';for(const c of [...view.controls].sort((a,b)=>(a.z||0)-(b.z||0))){if(c.type!=='radio'){group='';continue}if(c.var||!group)group=`imported-radio-${view.id}-${c.id}`;c.radioGroup=group}}applyGuiMetadata(decodeGuiMetadata(text),tabs,dialogs);state.tabs=tabs;state.dialogs=dialogs;state.activeType='tab';state.activeId=tabs[0].id;state.selectedControlId=null;state.imported={sourceName:name,preludeCode:cleanImportedCode(extractPrelude(lines,first)),postludeCode:cleanImportedCode(lines.slice(lastShow+1).join('\n')),encoding:state.imported?.encoding||'',parseWarnings:skipped};resetGuiTestSession();return {tabs:tabs.length,dialogs:dialogs.length,controls:[...tabs,...dialogs].reduce((n,v)=>n+v.controls.length,0),skipped:skipped.length}
}

async function decodeXmlFile(file){const buf=await file.arrayBuffer(),bytes=new Uint8Array(buf.slice(0,160)),head=String.fromCharCode(...bytes),m=head.match(/encoding=["']([^"']+)/i);let enc=(m?.[1]||'utf-8').toLowerCase();if(['euc-kr','ksc5601','windows-949','ks_c_5601-1987'].includes(enc))enc='euc-kr';try{return new TextDecoder(enc).decode(buf)}catch{return new TextDecoder('utf-8').decode(buf)}}
async function importXml(file){const txt=await decodeXmlFile(file),doc=new DOMParser().parseFromString(txt,'text/xml');if(doc.querySelector('parsererror'))throw new Error('XML을 읽지 못했습니다.');const images=[];for(const node of [...doc.querySelectorAll('GENERAL > *')]){if(!/^Image_\d+$/.test(node.tagName))continue;const name=node.querySelector(':scope > Name')?.textContent?.trim();if(name)images.push(name)}state.xmlImages=images;state.xmlMeta={name:file.name,count:images.length,xmlVersion:doc.querySelector('MAIN > XmlVersion')?.textContent?.trim()||'',targetName:doc.querySelector('TW > TWAName')?.textContent?.trim()||''};return images.length}
$('#importPreScript').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const preferred=$('#preScriptEncoding')?.value||'auto';const decoded=await readTextFileSmart(f,preferred);if((decoded.text.match(/�/g)||[]).length>0)throw new Error('문자 인코딩을 정상 해석하지 못했습니다. 인코딩을 CP949/EUC-KR로 지정해서 다시 불러와 보세요.');state.imported.encoding=decoded.encoding;const result=importPreScript(decoded.text,f.name);state.imported.encoding=decoded.encoding;state.showGrid=false;toast(`${result.tabs}개 탭, ${result.controls}개 컨트롤 · ${decoded.encoding}${result.skipped?` · 미해석 ${result.skipped}`:''}`);renderAll();requestAnimationFrame(fitCanvas)}catch(err){alert(err.message)}e.target.value=''})
$('#importGuiXml').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const n=await importXml(f);toast(`${n}개 ImageMax 이미지를 연결했습니다.`);renderAll()}catch(err){alert(err.message)}e.target.value=''})
function renderImportSummary(){const a=state.imported?.sourceName?`GUI: ${state.imported.sourceName}${state.imported.encoding?' · '+state.imported.encoding:''}`:'GUI: 새 작업';let b='XML: 연결 안 됨';if(state.xmlMeta){b=`XML: ${state.xmlMeta.name} · 이미지 ${state.xmlMeta.count}개`;if(state.xmlMeta.xmlVersion)b+=` · v${state.xmlMeta.xmlVersion}`;if(state.xmlMeta.targetName)b+=` · ${state.xmlMeta.targetName}`}el.importSummary.innerHTML=`<b>${html(a)}</b><br>${html(b)}${state.imported?.sourceName?'<br><span>한글·탭 이름·컨트롤 텍스트를 원본 인코딩으로 해석했습니다.</span>':''}${state.imported?.parseWarnings?.length?`<br><span class="warn-text">미해석 GUI 구문 ${state.imported.parseWarnings.length}개 · 고급 Lua에서 확인</span>`:''}`}

const zoomSelect=$('#zoomSelect');if(zoomSelect){zoomSelect.value=String(state.scale);zoomSelect.onchange=()=>{state.scale=Number(zoomSelect.value)||1;$('#zoomBadge').textContent=`${Math.round(state.scale*100)}%`;renderCanvas();persist()};$('#zoomBadge').textContent=`${Math.round(state.scale*100)}%`;}
function fitCanvas(){const wrap=$('#canvasWrap'),view=activeView();if(!wrap||!view)return;const outer=runtimeOuterSize(view);const availW=Math.max(260,wrap.clientWidth-56),availH=Math.max(260,wrap.clientHeight-56);const next=Math.max(.75,Math.min(1,availW/outer.w,availH/outer.h));state.scale=Math.round(next*20)/20;if($('#zoomSelect')){const opts=[.75,1,1.25,1.5,2];const closest=opts.reduce((a,b)=>Math.abs(b-state.scale)<Math.abs(a-state.scale)?b:a);$('#zoomSelect').value=String(closest)}$('#zoomBadge').textContent=`${Math.round(state.scale*100)}%`;renderCanvas();persist()}
if($('#fitCanvas'))$('#fitCanvas').onclick=fitCanvas;
document.addEventListener('keydown',e=>{const c=selectedControl();if(!c||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;e.preventDefault();const step=e.shiftKey?5:1,{w:W,h:H}=viewSize();if(e.key==='ArrowLeft')c.x=clamp(c.x-step,0,W);if(e.key==='ArrowRight')c.x=clamp(c.x+step,0,W);if(e.key==='ArrowUp')c.y=clamp(c.y-step,0,H);if(e.key==='ArrowDown')c.y=clamp(c.y+step,0,H);renderCanvas();renderInspector();renderLua();renderValidation();persist()});
$('#copyGuiLua').onclick=()=>copyText(generateLua());$('#downloadGuiLua').onclick=()=>{const issues=validate(),err=issues.filter(x=>x.level==='error').length;if(err&&!confirm(`검사 오류가 ${err}개 있습니다. 그래도 저장할까요?`))return;download('PreScript.lua','\ufeff'+generateLua())};
el.testButton.onclick=()=>{guiTestMode=!guiTestMode;resetGuiTestSession();el.testButton.textContent=guiTestMode?'편집으로 돌아가기':'동작 테스트';el.testButton.classList.toggle('primary',!guiTestMode);el.testButton.classList.toggle('soft',guiTestMode);el.testPanel.hidden=!guiTestMode;el.testPanel.closest('.workspace')?.classList.toggle('test-active',guiTestMode);if(guiTestMode){state.selectedControlId=null;guiTestLog('시작',`${activeView()?.name||'화면'} · 실제 ImageMax 명령은 실행하지 않습니다.`)}renderCanvas();renderInspector();renderBehaviorSection()};
$('#clearGuiTest').onclick=()=>{el.testLog.innerHTML='';guiTestSequence=0};
function persist(){try{localStorage.setItem('imagemaxGuiProject',encodeProject({...state,selectedControlId:null}))}catch{}}
$('#saveGuiProject').onclick=()=>download('imagemax_gui.imxgui.json',encodeProject({...state,selectedControlId:null}),'application/json');
$('#loadGuiProject').addEventListener('change',async e=>{try{const p=await readJsonFile(e.target.files[0]);if(p.format!=='imagemax-web-gui')throw new Error('ImageMax GUI Builder 프로젝트가 아닙니다.');Object.assign(state,p,{selectedControlId:null});normalizeState();resetGuiTestSession();if(!activeView()){state.activeType='tab';state.activeId=state.tabs[0]?.id||null}if($('#zoomSelect')){$('#zoomSelect').value=String(state.scale);$('#zoomBadge').textContent=`${Math.round(state.scale*100)}%`;}renderAll();if(guiTestMode)guiTestLog('시작',`${activeView()?.name||'화면'} · 새 프로젝트 테스트 상태`);toast('GUI 프로젝트를 불러왔습니다.')}catch(err){alert(err.message)}e.target.value=''});
$('#newGui').onclick=()=>{if(!confirm('GUI 작업을 초기화할까요?'))return;state.tabs=[{id:uid('tab'),name:'사용자',iniSection:'',controls:[]}];state.dialogs=[];state.activeType='tab';state.activeId=state.tabs[0].id;state.selectedControlId=null;state.xmlImages=[];state.xmlMeta=null;state.imported={sourceName:'',preludeCode:'',postludeCode:'',encoding:'',parseWarnings:[]};state.scale=1;state.showGrid=false;resetGuiTestSession();if($('#zoomSelect'))$('#zoomSelect').value='1';renderAll();if(guiTestMode)guiTestLog('시작','사용자 · 새 GUI 테스트 상태')};

try{const p=JSON.parse(localStorage.getItem('imagemaxGuiProject')||'null');if(p?.format==='imagemax-web-gui'){Object.assign(state,p,{selectedControlId:null});normalizeState()}}catch{}
if($('#zoomSelect')){$('#zoomSelect').value=String(state.scale);$('#zoomBadge').textContent=`${Math.round(state.scale*100)}%`;}
renderAll();
