import {$,$$,escLua,sanitizeId,luaId,download,downloadBytes,makeStoreZip,copyText,toast,encodeProject,readJsonFile,html} from '../assets/common.js';

const state={xmlName:'',images:[],selected:null,scripts:{},imageFiles:new Map(),imageFolderStats:null,version:2,previewUrl:null};
const els={xml:$('#xmlFile'),search:$('#imageSearch'),list:$('#imageList'),count:$('#imageCount'),preview:$('#previewBox'),folder:$('#imageFolder'),folderStatus:$('#folderStatus'),title:$('#workspaceTitle'),sub:$('#workspaceSub'),rules:$('#ruleList'),details:$('#imageDetails'),lua:$('#luaPreview'),badge:$('#assignedBadge'),addC:$('#addConditional'),addN:$('#addCounter'),addR:$('#addRetry'),copy:$('#copyLua'),dl:$('#downloadLua'),recipeList:$('#recipeList'),recipeSearch:$('#recipeSearch'),recipeCategory:$('#recipeCategory')};

const conditionDefs={
  current:{label:'현재 이미지 액션이 실행되었을 때 (재검색 없음)',fields:[]},
  found:{label:'다른 이미지를 이번 순회에서 1회 찾아서 발견했을 때',fields:[['image','확인할 이미지','image'],['accuracy','정확도(선택)','number']]},
  notfound:{label:'다른 이미지를 이번 순회에서 1회 찾아서 없을 때',fields:[['image','확인할 이미지','image'],['accuracy','정확도(선택)','number']]},
  enabled:{label:'이미지가 활성 상태일 때',fields:[['image','대상 이미지','image']]},
  disabled:{label:'이미지가 비활성 상태일 때',fields:[['image','대상 이미지','image']]},
  variable:{label:'GUI/전역 변수 값을 비교할 때',fields:[['varName','변수 이름','text'],['operator','비교','operator'],['value','비교 값','text']]},
  multi:{label:'MultiImage 조건식이 맞을 때',fields:[['expression','조건식 (&=AND, |=OR)','text']]},
  pixel:{label:'픽셀 RGB가 같을 때',fields:[['x','X','number'],['y','Y','number'],['r','R','number'],['g','G','number'],['b','B','number']]},
  stopped:{label:'ImageMax가 Stop 상태일 때',fields:[]},
  paused:{label:'ImageMax가 Pause 상태일 때',fields:[]}
};
const actionDefs={
  currentClick:{label:'현재 인식 이미지 클릭 (재검색 없음)',fields:[]},
  click:{label:'다른 이미지 검색 후 클릭',fields:[['image','대상 이미지','image'],['offsetX','X 오프셋','number'],['offsetY','Y 오프셋','number']]},
  forceClick:{label:'등록 위치 강제 클릭',fields:[['image','대상 이미지','image']]},
  enable:{label:'이미지 활성/비활성',fields:[['image','대상 이미지','image'],['enabled','상태','boolean']]},
  goto:{label:'인식 순서 이동',fields:[['image','이동할 이미지','image']]},
  key:{label:'키보드 입력',fields:[['text','ImageMax 키 문자열','text'],['speed','속도','speed'],['type','입력 방식','inputType']]},
  mouse:{label:'좌표 클릭',fields:[['x','X','number'],['y','Y','number'],['randX','랜덤 X','number'],['randY','랜덤 Y','number']]},
  drag:{label:'마우스 드래그',fields:[['x1','시작 X','number'],['y1','시작 Y','number'],['x2','종료 X','number'],['y2','종료 Y','number'],['press1','시작 누름(초)','number'],['press2','종료 누름(초)','number']]},
  setVar:{label:'변수 값 지정',fields:[['varName','변수 이름','text'],['value','값','text']]},
  sleep:{label:'짧은 딜레이',fields:[['ms','밀리초','number']]},
  openScript:{label:'다른 ImageMax 스크립트 열기',fields:[['name','스크립트 이름','text']]},
  stop:{label:'ImageMax 중지',fields:[]},
  sound:{label:'사운드 재생',fields:[['file','WAV 파일명','text'],['sec','재생/대기 초','number']]},
  screenshot:{label:'스크린샷 저장',fields:[]},
  print:{label:'로그 출력',fields:[['text','메시지','text']]},
  passAct:{label:'다음 N개 액션 건너뛰기',fields:[['count','개수','number']]},
  passAll:{label:'현재 이미지의 이후 액션 모두 건너뛰기',fields:[]},
  fail:{label:'인식 실패 액션으로 이동',fields:[]}
};

const recipeDefs=[
  {id:'currentClick',category:'basic',title:'현재 이미지 → 클릭',desc:'현재 리스트 이미지가 이미 인식된 상태이므로 다시 검색하지 않고 바로 클릭합니다.',tag:'가장 많이 사용',make:()=>conditional('current',[act('currentClick')])},
  {id:'currentKey',category:'basic',title:'현재 이미지 → 키 입력',desc:'현재 이미지가 인식되면 Space·Enter·ESC 등 ImageMax 키 입력을 1회 실행합니다.',tag:'기본',make:()=>conditional('current',[act('key',{text:'<Space>',speed:'FASTER',type:'MKEVENT'})])},
  {id:'currentPass',category:'flow',title:'현재 이미지 → 이후 액션 건너뛰기',desc:'조건이 만족된 현재 이미지에서 뒤쪽 액션을 실행하지 않도록 PassAllAct를 호출합니다.',tag:'액션 흐름',make:()=>conditional('current',[act('passAll')])},
  {id:'foundClick',category:'image',title:'다른 이미지 발견 → 그 이미지 클릭',desc:'선택한 다른 이미지를 이번 호출에서 딱 한 번 검색하고 발견하면 클릭합니다.',tag:'이미지명만 변경',make:()=>{const other=firstOther();return conditional('found',[act('currentClick')],[],{image:other,accuracy:''})}},
  {id:'notFoundFail',category:'flow',title:'다른 이미지가 없으면 → 실패 액션',desc:'다른 이미지를 1회 확인하여 없을 때 GotoFailAct로 이동합니다.',tag:'실패 처리',make:()=>{const other=firstOther();return conditional('notfound',[act('fail')],[],{image:other,accuracy:''})}},
  {id:'foundPass',category:'flow',title:'다른 이미지 발견 → 다음 N개 액션 패스',desc:'다른 이미지를 확인한 뒤 발견되면 PassAct로 지정 개수만큼 액션을 건너뜁니다.',tag:'분기',make:()=>{const other=firstOther();return conditional('found',[act('passAct',{count:1})],[],{image:other,accuracy:''})}},
  {id:'count',category:'state',title:'현재 이미지 N회 인식 후 실행',desc:'스크립트가 호출될 때마다 카운트하고 N번째 호출에서만 행동합니다. 반복문을 사용하지 않습니다.',tag:'상태',make:()=>({kind:'counter',varName:`image_count_${selectedImage()?.index||1}`,threshold:3,actions:[act('currentClick')]})},
  {id:'retry',category:'state',title:'다른 이미지 최대 N회 순회 재확인',desc:'한 호출당 ImageSearch 1회만 수행합니다. 못 찾으면 다음 ImageMax 리스트 순회에서 다시 확인합니다.',tag:'비차단',make:()=>({kind:'retry',image:firstOther(),varName:`recheck_count_${selectedImage()?.index||1}`,attempts:5,foundActions:[act('print',{text:'대상 이미지 발견'})],missActions:[],exhaustedActions:[act('print',{text:'최대 순회 횟수 도달'})]})},
  {id:'guiVar',category:'state',title:'GUI/전역 변수 조건 → 변수 값 지정',desc:'PreScript GUI의 check_* 값처럼 전역 변수를 비교하고 다른 상태 변수를 변경합니다.',tag:'GUI 연계',make:()=>conditional('variable',[act('setVar',{varName:'result_bool',value:'1'})],[],{varName:'check_option',operator:'==',value:'1'})},
  {id:'elapsed',category:'state',title:'N초 경과 후 실행 (Sleep 없이)',desc:'첫 호출 시간을 기억하고 이후 순회에서 경과 시간을 확인합니다. 대기 중에도 ImageMax 순회를 막지 않습니다.',tag:'비차단 시간',make:()=>({kind:'elapsed',varName:`elapsed_${selectedImage()?.index||1}`,seconds:60,actions:[act('currentClick')],reset:true})},
  {id:'randomFound',category:'image',title:'여러 이미지 중 발견된 것 하나 랜덤 클릭',desc:'선택한 이미지 목록을 한 번씩만 확인하고, 발견된 후보 중 하나만 랜덤으로 클릭합니다.',tag:'예제 기반',make:()=>({kind:'randomFound',images:defaultCandidates(),maxImages:20})},
  {id:'bestMatch',category:'image',title:'여러 후보 중 정확도 가장 높은 이미지 선택',desc:'같은 ROI에 겹치는 후보를 각각 한 번 검색하고 정확도가 가장 높은 결과 하나만 클릭합니다.',tag:'예제 기반',make:()=>({kind:'bestMatch',images:defaultCandidates(),minAccuracy:80})},
  {id:'screenshot',category:'utility',title:'현재 이미지 → 스크린샷 저장',desc:'현재 이미지 액션이 호출되면 SaveScreenshot()을 한 번 실행합니다.',tag:'기록',make:()=>conditional('current',[act('screenshot')])},
  {id:'log',category:'utility',title:'현재 이미지 → 로그 남기기',desc:'디버깅을 위해 현재 이미지가 실행되었다는 로그를 한 번 출력합니다.',tag:'디버깅',make:()=>conditional('current',[act('print',{text:'현재 이미지 액션 실행'})])}
];

function act(type,params={}){return {type,params}}
function conditional(type,then=[],els=[],params={}){return {kind:'conditional',condition:{type,params},then,else:els}}
function selectedImage(){return state.images.find(i=>i.name===state.selected)}
function firstOther(){return state.images.find(i=>i.name!==state.selected&&!i.name.toLowerCase().endsWith('.grp'))?.name||state.images.find(i=>i.name!==state.selected)?.name||''}
function defaultCandidates(){return state.images.filter(i=>i.name!==state.selected&&!i.name.toLowerCase().endsWith('.grp')).slice(0,4).map(i=>i.name)}

function decodeXml(buffer){
  const bytes=new Uint8Array(buffer.slice(0,180));let head='';for(const b of bytes)head+=String.fromCharCode(b);
  const m=head.match(/encoding=["']([^"']+)/i);const declared=(m?.[1]||'utf-8').toLowerCase();
  const candidates=declared.includes('euc')||declared.includes('949')||declared.includes('5601')?['euc-kr','utf-8']:['utf-8','euc-kr'];
  for(const enc of candidates){try{return {text:new TextDecoder(enc,{fatal:true}).decode(buffer),encoding:enc==='euc-kr'?'CP949 / EUC-KR':'UTF-8'}}catch{}}
  return {text:new TextDecoder('euc-kr').decode(buffer),encoding:'CP949 / EUC-KR'};
}
function parseTuple(v=''){return v.replace(/[()]/g,'').split(',').map(x=>Number(x.trim())||0)}
function parseXml(text){
  const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw new Error('XML 파싱 오류');
  const nodes=[...doc.querySelectorAll('GENERAL > *')].filter(n=>/^Image_\d+$/.test(n.tagName));
  return nodes.map((n,index)=>{const q=s=>n.querySelector(`:scope > ${s}`),trg=q('Trg');const actions=[...n.children].filter(c=>/^Act_\d+$/.test(c.tagName)).map(a=>({name:a.querySelector(':scope > Name')?.textContent||'',enabled:a.querySelector(':scope > Enable')?.textContent!=='0',param:a.querySelector(':scope > Param')?.textContent||'',luaFile:a.querySelector(':scope > Attr')?.getAttribute('LuaFile')||'',luaText:a.querySelector(':scope > Attr')?.getAttribute('Text')||''}));return {index:index+1,name:q('Name')?.textContent||`Image_${index+1}`,rect:parseTuple(q('Rect')?.textContent),roi:parseTuple(q('ROI')?.textContent),enabled:q('Enable')?.textContent!=='0',group:Number(q('Group')?.textContent)||0,accuracy:Number(trg?.getAttribute('Acc'))||80,actions}});
}

function normalizeKey(name=''){return String(name).normalize('NFC').trim().replace(/\.[^.\\/]+$/,'').toLowerCase()}
function isImageFile(file){return /\.(png|jpe?g|gif|webp|bmp)$/i.test(file.name)||String(file.type).startsWith('image/')}
function findImageFile(name){return state.imageFiles.get(normalizeKey(name))||null}
function rebuildFolderIndex(files){state.imageFiles.clear();let usable=0,duplicates=0;for(const f of files){if(!isImageFile(f))continue;usable++;const key=normalizeKey(f.name);if(state.imageFiles.has(key)){duplicates++;continue}state.imageFiles.set(key,f)}const previewable=state.images.filter(i=>!i.name.toLowerCase().endsWith('.grp'));const matched=previewable.filter(i=>findImageFile(i.name)).length;state.imageFolderStats={totalFiles:files.length,usable,matched,target:previewable.length,duplicates};renderFolderStatus();renderImages();renderPreview()}
function renderFolderStatus(){const s=state.imageFolderStats;if(!s){els.folderStatus.textContent='아직 폴더를 연결하지 않았습니다.';return}els.folderStatus.innerHTML=`<b>${s.matched}/${s.target}</b>개 XML 이미지 연결 · 이미지 파일 ${s.usable}개 읽음${s.target-s.matched>0?` · <span class="warn-text">미연결 ${s.target-s.matched}개</span>`:''}${s.duplicates?` · <span class="warn-text">중복 이름 ${s.duplicates}개</span>`:''}`}

els.xml.addEventListener('change',async()=>{const f=els.xml.files[0];if(!f)return;try{const buf=await f.arrayBuffer();const {text,encoding}=decodeXml(buf);state.images=parseXml(text);state.xmlName=f.name;state.scripts={};state.selected=null;els.search.disabled=false;if(els.folder.files?.length)rebuildFolderIndex([...els.folder.files]);renderImages();renderSelection();renderRecipes();persist();toast(`${state.images.length}개 이미지 로드 · ${encoding}`)}catch(e){alert(`XML을 읽지 못했습니다: ${e.message}`)}});
els.search.addEventListener('input',renderImages);
els.folder.addEventListener('change',()=>rebuildFolderIndex([...els.folder.files]));
els.recipeSearch.addEventListener('input',renderRecipes);els.recipeCategory.addEventListener('change',renderRecipes);

function renderImages(){const q=els.search.value.trim().toLowerCase();const list=state.images.filter(i=>i.name.toLowerCase().includes(q));els.count.textContent=String(list.length);els.list.innerHTML=list.map(i=>{const file=findImageFile(i.name),isGroup=i.name.toLowerCase().endsWith('.grp');return `<button class="image-item ${state.selected===i.name?'active':''}" data-name="${html(i.name)}"><div><div class="image-name">${html(i.name)}</div><div class="image-meta">Image_${i.index} · Acc ${i.accuracy}% · Group ${i.group}</div></div><div class="image-badges">${file?'<span class="badge ok">미리보기</span>':isGroup?'<span class="badge">GROUP</span>':''}<span class="badge ${i.enabled?'ok':''}">${i.enabled?'ON':'OFF'}</span></div></button>`}).join('')||'<div class="hint">일치하는 이미지가 없습니다.</div>';$$('.image-item',els.list).forEach(x=>x.onclick=()=>selectImage(x.dataset.name))}
function selectImage(name){state.selected=name;if(!state.scripts[name])state.scripts[name]=[];renderImages();renderSelection();renderRecipes();persist()}
function renderSelection(){const img=selectedImage(),active=!!img;els.addC.disabled=els.addN.disabled=els.addR.disabled=els.copy.disabled=els.dl.disabled=!active;els.title.textContent=active?img.name:'이미지를 먼저 선택하세요';els.sub.textContent=active?`Image_${img.index} · ROI (${img.roi.join(', ')}) · 정확도 ${img.accuracy}% · 현재 액션에 넣을 1회 실행 Lua`:'XML 이미지 하나를 선택하면 해당 ImageMax 액션에 넣을 스크립트를 만듭니다.';els.badge.textContent=active?`${(state.scripts[img.name]||[]).length} 블록`:'미선택';renderPreview();renderDetails();renderRules();renderLua()}
function renderPreview(){if(state.previewUrl){URL.revokeObjectURL(state.previewUrl);state.previewUrl=null}const img=selectedImage();if(!img){els.preview.innerHTML='선택 이미지 정보가 여기에 표시됩니다.';return}if(img.name.toLowerCase().endsWith('.grp')){els.preview.innerHTML=`<div class="preview-placeholder"><b>${html(img.name)}</b><span>.grp는 ImageMax 그룹 항목이라 단일 이미지 미리보기가 없습니다.</span></div>`;return}const f=findImageFile(img.name);if(f){state.previewUrl=URL.createObjectURL(f);els.preview.innerHTML=`<img src="${state.previewUrl}" alt="${html(img.name)}"><div class="preview-caption"><b>${html(img.name)}</b><span>${html(f.webkitRelativePath||f.name)}</span></div>`;return}els.preview.innerHTML=`<div class="preview-placeholder"><b>${html(img.name)}</b><span>연결된 이미지 파일을 찾지 못했습니다.</span><small>폴더 안 파일명이 XML 이미지명과 같으면 자동 연결됩니다.</small></div>`}
function renderDetails(){const img=selectedImage();if(!img){els.details.innerHTML='<div class="hint">이미지를 선택하면 ROI, 정확도, 활성상태와 기존 액션을 확인할 수 있습니다.</div>';return}const stack=img.actions.map((a,i)=>`<details class="existing"><summary><b>Act_${i+1} · ${html(a.name||'액션')}</b>${a.enabled?'':' · 비활성'}</summary>${a.luaFile?`<div class="hint" style="margin-top:6px">LuaFile: ${html(a.luaFile)}</div><pre>${html(a.luaText||a.param)}</pre>`:`<div class="hint" style="margin-top:6px">${html(a.param||'')}</div>`}</details>`).join('');els.details.innerHTML=`<dl class="kv compact-kv"><dt>Rect</dt><dd>(${img.rect.join(', ')})</dd><dt>ROI</dt><dd>(${img.roi.join(', ')})</dd><dt>정확도</dt><dd>${img.accuracy}%</dd><dt>상태</dt><dd>${img.enabled?'활성':'비활성'}</dd><dt>그룹</dt><dd>${img.group}</dd><dt>액션</dt><dd>${img.actions.length}개</dd></dl>${stack?`<div class="section-label" style="margin-top:12px">기존 Action List</div>${stack}`:'<div class="hint" style="margin-top:10px">등록된 액션이 없습니다.</div>'}`}

function renderRecipes(){const q=els.recipeSearch.value.trim().toLowerCase(),cat=els.recipeCategory.value;const list=recipeDefs.filter(r=>(cat==='all'||r.category===cat)&&(`${r.title} ${r.desc} ${r.tag}`.toLowerCase().includes(q)));els.recipeList.innerHTML=list.map(r=>`<article class="recipe-card"><div class="recipe-card-top"><span class="recipe-tag">${html(r.tag)}</span><span class="recipe-cat">${{basic:'기본',image:'이미지',state:'상태',flow:'흐름',utility:'기록'}[r.category]}</span></div><h3>${html(r.title)}</h3><p>${html(r.desc)}</p><button class="btn small ${state.selected?'primary':''}" data-apply-recipe="${r.id}" ${state.selected?'':'disabled'}>${state.selected?'이 이미지에 적용':'이미지 선택 필요'}</button></article>`).join('')||'<div class="hint">일치하는 템플릿이 없습니다.</div>';$$('[data-apply-recipe]',els.recipeList).forEach(b=>b.onclick=()=>applyRecipe(b.dataset.applyRecipe))}
function applyRecipe(id){if(!state.selected)return toast('왼쪽에서 ImageMax 이미지를 먼저 선택하세요.');const r=recipeDefs.find(x=>x.id===id);if(!r)return;state.scripts[state.selected].push(r.make());renderSelection();persist();toast(`'${r.title}' 템플릿을 추가했습니다.`)}

function imageOptions(value=''){return `<option value="">-- 이미지 선택 --</option>${state.images.map(i=>`<option ${i.name===value?'selected':''} value="${html(i.name)}">${html(i.name)}</option>`).join('')}`}
function fieldHtml(field,value){const [key,label,type]=field;let control='';if(type==='image')control=`<select class="select" data-k="${key}">${imageOptions(value)}</select>`;else if(type==='operator')control=`<select class="select" data-k="${key}">${['==','~=','>','>=','<','<='].map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select>`;else if(type==='boolean')control=`<select class="select" data-k="${key}"><option value="true" ${value!=='false'?'selected':''}>활성(true)</option><option value="false" ${value==='false'?'selected':''}>비활성(false)</option></select>`;else if(type==='speed')control=`<select class="select" data-k="${key}">${['FASTEST','FASTER','NORMAL','SLOWER','SLOWEST'].map(x=>`<option ${x===(value||'FASTER')?'selected':''}>${x}</option>`).join('')}</select>`;else if(type==='inputType')control=`<select class="select" data-k="${key}"><option ${value!=='MESSAGE'?'selected':''}>MKEVENT</option><option ${value==='MESSAGE'?'selected':''}>MESSAGE</option></select>`;else control=`<input class="input" data-k="${key}" type="${type==='number'?'number':'text'}" value="${html(value??'')}">`;return `<div class="field"><label>${label}</label>${control}</div>`}
function actionCard(a,ri,branch,ai){const def=actionDefs[a.type]||actionDefs.currentClick;return `<div class="action-card" data-branch="${branch}" data-ai="${ai}"><div class="row"><select class="select action-type grow">${Object.entries(actionDefs).map(([k,v])=>`<option value="${k}" ${k===a.type?'selected':''}>${v.label}</option>`).join('')}</select><button class="btn danger small remove-action" type="button">삭제</button></div>${def.fields.length?`<div class="rule-grid action-fields">${def.fields.map(f=>fieldHtml(f,a.params?.[f[0]])).join('')}</div>`:''}</div>`}
function ruleShell(title,desc,body,ri){return `<details class="rule" data-ri="${ri}" ${ri===(state.scripts[state.selected]?.length||1)-1?'open':''}><summary class="rule-head"><div><span class="rule-title">${html(title)}</span><span class="rule-desc">${html(desc)}</span></div><div class="rule-actions"><button class="btn small move-up" type="button">↑</button><button class="btn small move-down" type="button">↓</button><button class="btn danger small remove-rule" type="button">삭제</button></div></summary><div class="rule-body">${body}</div></details>`}
function conditionalHtml(r,ri){const def=conditionDefs[r.condition.type]||conditionDefs.current;const body=`<div class="field"><label>조건</label><select class="select cond-type">${Object.entries(conditionDefs).map(([k,v])=>`<option value="${k}" ${k===r.condition.type?'selected':''}>${v.label}</option>`).join('')}</select></div><div class="rule-grid cond-fields">${def.fields.map(f=>fieldHtml(f,r.condition.params?.[f[0]])).join('')}</div><div class="branch"><div class="branch-head"><b>조건이 맞으면</b><button class="btn small add-action" data-branch="then" type="button">+ 행동</button></div><div class="action-list">${r.then.map((a,i)=>actionCard(a,ri,'then',i)).join('')||'<div class="hint">행동 없음</div>'}</div></div><div class="branch optional"><div class="branch-head"><b>아니면 (선택)</b><button class="btn small add-action" data-branch="else" type="button">+ 행동</button></div><div class="action-list">${r.else.map((a,i)=>actionCard(a,ri,'else',i)).join('')||'<div class="hint">행동 없음</div>'}</div></div>`;return ruleShell(`조건 블록 ${ri+1}`,def.label,body,ri)}
function counterHtml(r,ri){const body=`<div class="rule-grid">${fieldHtml(['varName','카운터 변수','text'],r.varName)}${fieldHtml(['threshold','N회 이상','number'],r.threshold)}</div><div class="branch"><div class="branch-head"><b>N회 도달 후</b><button class="btn small add-action" data-branch="actions" type="button">+ 행동</button></div><div class="action-list">${r.actions.map((a,i)=>actionCard(a,ri,'actions',i)).join('')}</div></div>`;return ruleShell(`N회 인식 상태 ${ri+1}`,'호출 1회 = 카운트 1회. 반복문 없이 다음 ImageMax 순회까지 상태를 유지합니다.',body,ri)}
function retryHtml(r,ri){const body=`<div class="rule-grid">${fieldHtml(['image','1회 확인할 이미지','image'],r.image)}${fieldHtml(['varName','재확인 변수','text'],r.varName)}${fieldHtml(['attempts','최대 순회 횟수','number'],r.attempts)}</div><div class="branch"><div class="branch-head"><b>찾았을 때</b><button class="btn small add-action" data-branch="foundActions" type="button">+ 행동</button></div><div class="action-list">${r.foundActions.map((a,i)=>actionCard(a,ri,'foundActions',i)).join('')}</div></div><div class="branch optional"><div class="branch-head"><b>최대 횟수 도달</b><button class="btn small add-action" data-branch="exhaustedActions" type="button">+ 행동</button></div><div class="action-list">${(r.exhaustedActions||[]).map((a,i)=>actionCard(a,ri,'exhaustedActions',i)).join('')||'<div class="hint">행동 없음</div>'}</div></div>`;return ruleShell(`순회 재확인 ${ri+1}`,'한 호출에서 ImageSearch는 1회만 실행하고 즉시 반환합니다.',body,ri)}
function elapsedHtml(r,ri){const body=`<div class="rule-grid">${fieldHtml(['varName','시간 변수','text'],r.varName)}${fieldHtml(['seconds','경과 초','number'],r.seconds)}</div><div class="branch"><div class="branch-head"><b>시간 도달 후</b><button class="btn small add-action" data-branch="actions" type="button">+ 행동</button></div><div class="action-list">${r.actions.map((a,i)=>actionCard(a,ri,'actions',i)).join('')}</div></div>`;return ruleShell(`비차단 경과시간 ${ri+1}`,'Sleep로 기다리지 않고 호출 사이의 os.clock() 경과를 비교합니다.',body,ri)}
function multiImageSelect(images=[]){return `<div class="field"><label>후보 이미지 (Ctrl/Shift로 여러 개 선택)</label><select class="select multi-images" multiple size="7">${state.images.filter(i=>!i.name.toLowerCase().endsWith('.grp')).map(i=>`<option value="${html(i.name)}" ${images.includes(i.name)?'selected':''}>${html(i.name)}</option>`).join('')}</select></div>`}
function randomHtml(r,ri){return ruleShell(`여러 이미지 중 랜덤 클릭 ${ri+1}`,'선택 후보를 각각 최대 1회 검색하고 발견된 결과 중 하나만 클릭합니다. 후보는 최대 20개입니다.',multiImageSelect(r.images),ri)}
function bestHtml(r,ri){return ruleShell(`최고 정확도 후보 선택 ${ri+1}`,'후보별 ImageSearch를 1회씩 수행하고 정확도가 가장 높은 하나만 클릭합니다. 후보는 최대 20개입니다.',`${multiImageSelect(r.images)}${fieldHtml(['minAccuracy','최소 정확도','number'],r.minAccuracy)}`,ri)}
function renderRules(){const img=selectedImage();if(!img){els.rules.innerHTML='<div class="empty"><div><b>XML → 이미지 선택 → 템플릿 선택</b><p class="hint">Lua 문법을 입력할 필요가 없습니다.</p></div></div>';return}const rules=state.scripts[img.name]||[];els.rules.innerHTML=rules.length?rules.map((r,i)=>r.kind==='counter'?counterHtml(r,i):r.kind==='retry'?retryHtml(r,i):r.kind==='elapsed'?elapsedHtml(r,i):r.kind==='randomFound'?randomHtml(r,i):r.kind==='bestMatch'?bestHtml(r,i):conditionalHtml(r,i)).join(''):'<div class="empty"><div><b>아직 스크립트 블록이 없습니다.</b><p class="hint">위의 자주 쓰는 템플릿 하나를 선택하면 기본 구성이 자동으로 만들어집니다.</p></div></div>';bindRuleEvents()}
function readActionCard(card,a){a.type=$('.action-type',card).value;const def=actionDefs[a.type]||actionDefs.currentClick;a.params=Object.fromEntries(def.fields.map(f=>[f[0],$(`[data-k="${f[0]}"]`,card)?.value??'']))}
function syncRule(ruleEl){const r=state.scripts[state.selected][Number(ruleEl.dataset.ri)];if(!r)return;if(r.kind==='conditional'){r.condition.type=$('.cond-type',ruleEl).value;const def=conditionDefs[r.condition.type]||conditionDefs.current;r.condition.params=Object.fromEntries(def.fields.map(f=>[f[0],$(`[data-k="${f[0]}"]`,$('.cond-fields',ruleEl))?.value??'']))}else if(r.kind==='counter'){r.varName=$('[data-k="varName"]',ruleEl).value;r.threshold=Number($('[data-k="threshold"]',ruleEl).value)||1}else if(r.kind==='retry'){r.image=$('[data-k="image"]',ruleEl).value;r.varName=$('[data-k="varName"]',ruleEl).value;r.attempts=Number($('[data-k="attempts"]',ruleEl).value)||1}else if(r.kind==='elapsed'){r.varName=$('[data-k="varName"]',ruleEl).value;r.seconds=Number($('[data-k="seconds"]',ruleEl).value)||0}else if(r.kind==='randomFound'||r.kind==='bestMatch'){r.images=[...$('.multi-images',ruleEl).selectedOptions].map(o=>o.value);if(r.images.length>20){r.images=r.images.slice(0,20);toast('한 액션에서 확인할 후보는 최대 20개로 제한했습니다.');}if(r.kind==='bestMatch')r.minAccuracy=Number($('[data-k="minAccuracy"]',ruleEl).value)||0}
  $$('.action-card',ruleEl).forEach(card=>{const branch=card.dataset.branch,ai=Number(card.dataset.ai);if(r[branch]?.[ai])readActionCard(card,r[branch][ai])});persist();renderLua();renderBadge()}
function bindRuleEvents(){$$('.rule',els.rules).forEach(ruleEl=>{ruleEl.addEventListener('change',e=>{const r=state.scripts[state.selected][Number(ruleEl.dataset.ri)];if(e.target.classList.contains('cond-type')){r.condition.type=e.target.value;r.condition.params=r.condition.type==='current'?{}:{image:firstOther()};renderRules();renderLua();persist();return}if(e.target.classList.contains('action-type')){const card=e.target.closest('.action-card'),a=r[card.dataset.branch][Number(card.dataset.ai)];a.type=e.target.value;a.params=a.type==='click'||a.type==='enable'||a.type==='goto'||a.type==='forceClick'?{image:firstOther()}:a.type==='key'?{text:'<Space>',speed:'FASTER',type:'MKEVENT'}:{};renderRules();renderLua();persist();return}syncRule(ruleEl)});$$('.rule-actions button',ruleEl).forEach(b=>b.addEventListener('click',e=>e.stopPropagation()));$('.remove-rule',ruleEl).onclick=e=>{e.preventDefault();state.scripts[state.selected].splice(Number(ruleEl.dataset.ri),1);renderSelection();persist()};$('.move-up',ruleEl).onclick=e=>{e.preventDefault();moveRule(Number(ruleEl.dataset.ri),-1)};$('.move-down',ruleEl).onclick=e=>{e.preventDefault();moveRule(Number(ruleEl.dataset.ri),1)};$$('.add-action',ruleEl).forEach(b=>b.onclick=e=>{e.preventDefault();syncRule(ruleEl);const r=state.scripts[state.selected][Number(ruleEl.dataset.ri)],branch=b.dataset.branch;r[branch].push(act('currentClick'));renderRules();renderLua();persist()});$$('.remove-action',ruleEl).forEach(b=>b.onclick=e=>{e.preventDefault();const card=b.closest('.action-card'),r=state.scripts[state.selected][Number(ruleEl.dataset.ri)];r[card.dataset.branch].splice(Number(card.dataset.ai),1);renderRules();renderLua();persist()})})}
function moveRule(i,d){const a=state.scripts[state.selected],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];renderRules();renderLua();persist()}
function renderBadge(){const img=selectedImage();if(img)els.badge.textContent=`${state.scripts[img.name]?.length||0} 블록`}

els.addC.onclick=()=>{state.scripts[state.selected].push(conditional('current',[act('currentClick')]));renderSelection();persist()};
els.addN.onclick=()=>applyRecipe('count');els.addR.onclick=()=>applyRecipe('retry');

function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function luaLiteral(v=''){const s=String(v).trim();if(/^[-+]?\d+(?:\.\d+)?$/.test(s)||s==='true'||s==='false'||s==='nil')return s;return escLua(s)}
function compileAction(a,indent=''){const p=a.params||{},line=s=>indent+s;switch(a.type){case'currentClick':return line('ImageClick()');case'click':{const x=num(p.offsetX),y=num(p.offsetY);return x||y?line(`ImageClick(${escLua(p.image)}, ${x}, ${y}, 5, 5, 0.5)`):line(`ImageClick(${escLua(p.image)})`)}case'forceClick':return line(`ImageClickForce(${escLua(p.image)})`);case'enable':return line(`EnableImage(${p.enabled!=='false'?'true':'false'}, ${escLua(p.image)})`);case'goto':return line(`GotoImage(${escLua(p.image)})`);case'key':return line(`Keybd(${escLua(p.text||'<Space>')}, ${p.speed||'FASTER'}, ${p.type||'MKEVENT'})`);case'mouse':return line(`Mouse(LBUTTON, CLICK, ${num(p.x)}, ${num(p.y)}, 0, 0, ${num(p.randX,5)}, ${num(p.randY,5)}, 0.5, 1, NORMAL, MKEVENT)`);case'drag':return line(`MouseDrag(LBUTTON, ${num(p.x1)}, ${num(p.y1)}, ${num(p.press1,.5)}, ${num(p.x2)}, ${num(p.y2)}, ${num(p.press2,.5)})`);case'setVar':return line(`${luaId(p.varName||'value')} = ${luaLiteral(p.value)}`);case'sleep':return line(`Sleep(${Math.max(0,num(p.ms,500))})`);case'openScript':return line(`OpenScript(${escLua(p.name)})`);case'stop':return line('Stop()');case'sound':return line(`PlaySound(${escLua(p.file||'alarm.wav')}, ${num(p.sec,3)})`);case'screenshot':return line('SaveScreenshot()');case'print':return line(`print(${escLua(p.text||'로그')})`);case'passAct':return line(`PassAct(${Math.max(1,num(p.count,1))})`);case'passAll':return line('PassAllAct()');case'fail':return line('GotoFailAct()');default:return line('-- 지원되지 않는 행동')}}
function compileCondition(c){const p=c.params||{};switch(c.type){case'current':return 'true';case'found':return p.accuracy?`ImageSearch(${escLua(p.image)}, ${num(p.accuracy)}, GetImageROI(${escLua(p.image)})) == 1`:`ImageSearch(${escLua(p.image)}) == 1`;case'notfound':return p.accuracy?`ImageSearch(${escLua(p.image)}, ${num(p.accuracy)}, GetImageROI(${escLua(p.image)})) == 0`:`ImageSearch(${escLua(p.image)}) == 0`;case'enabled':return `IsEnableImage(${escLua(p.image)}) == true`;case'disabled':return `IsEnableImage(${escLua(p.image)}) == false`;case'variable':return `${luaId(p.varName||'value')} ${p.operator||'=='} ${luaLiteral(p.value)}`;case'multi':return `MultiImage(${escLua(p.expression)}) == 1`;case'pixel':return `(function() local r,g,b=GetPixelRGB(${num(p.x)}, ${num(p.y)}); return r==${num(p.r)} and g==${num(p.g)} and b==${num(p.b)} end)()`;case'stopped':return 'IsStop() == 1';case'paused':return 'IsPause() == 1';default:return 'true'}}
function compileRule(r){
  if(r.kind==='counter'){const v=luaId(r.varName||'image_count');return `${v} = ${v} or 0\n${v} = ${v} + 1\nif ${v} >= ${Math.max(1,num(r.threshold,3))} then\n${r.actions.map(a=>compileAction(a,'    ')).join('\n')||'    -- 실행할 행동 없음'}\n    ${v} = 0\nend`}
  if(r.kind==='retry'){const img=r.image||'',v=luaId(r.varName||'recheck_count'),attempts=Math.max(1,num(r.attempts,5));return `${v} = ${v} or 0\nlocal ret = ImageSearch(${escLua(img)})\nif ret == 1 then\n${(r.foundActions||[]).map(a=>compileAction(a,'    ')).join('\n')||'    -- 발견 후 행동 없음'}\n    ${v} = 0\nelse\n    ${v} = ${v} + 1\n    if ${v} >= ${attempts} then\n${(r.exhaustedActions||[]).map(a=>compileAction(a,'        ')).join('\n')||'        -- 최대 횟수 도달'}\n        ${v} = 0\n    end\nend`}
  if(r.kind==='elapsed'){const v=luaId(r.varName||'elapsed_timer'),sec=Math.max(0,num(r.seconds,60));return `${v} = ${v} or os.clock()\nif os.clock() - ${v} >= ${sec} then\n${(r.actions||[]).map(a=>compileAction(a,'    ')).join('\n')||'    -- 실행할 행동 없음'}\n    ${v} = os.clock()\nend`}
  if(r.kind==='randomFound'){const names=(r.images||[]).slice(0,20);return `local _im_candidates = {${names.map(escLua).join(', ')}}\nlocal _im_found = {}\nfor _, _im_name in ipairs(_im_candidates) do\n    local ret, acc, ix, iy = ImageSearch(_im_name)\n    if ret == 1 then table.insert(_im_found, {name=_im_name, x=ix, y=iy}) end\nend\nif #_im_found > 0 then\n    local _im_pick = _im_found[math.random(#_im_found)]\n    Mouse(LBUTTON, CLICK, _im_pick.x, _im_pick.y)\nend`}
  if(r.kind==='bestMatch'){const names=(r.images||[]).slice(0,20),min=Math.max(0,num(r.minAccuracy,80));return `local _im_candidates = {${names.map(escLua).join(', ')}}\nlocal _im_best_acc, _im_best_name, _im_best_x, _im_best_y = ${min-1}, nil, nil, nil\nfor _, _im_name in ipairs(_im_candidates) do\n    local ret, acc, ix, iy = ImageSearch(_im_name)\n    if ret == 1 and acc >= ${min} and acc > _im_best_acc then\n        _im_best_acc, _im_best_name, _im_best_x, _im_best_y = acc, _im_name, ix, iy\n    end\nend\nif _im_best_name then\n    Mouse(LBUTTON, CLICK, _im_best_x, _im_best_y)\nend`}
  if(r.condition?.type==='current')return (r.then||[]).map(a=>compileAction(a)).join('\n')||'-- 실행할 행동 없음';const cond=compileCondition(r.condition),t=(r.then||[]).map(a=>compileAction(a,'    ')).join('\n')||'    -- 실행할 행동 없음',e=r.else?.length?`\nelse\n${r.else.map(a=>compileAction(a,'    ')).join('\n')}`:'';return `if ${cond} then\n${t}${e}\nend`}
function generatedLua(){if(!state.selected)return '-- 이미지를 선택하세요.';const rules=state.scripts[state.selected]||[];return `-- This is IM's script file. Do not remove this comment line.\n-- ImageMax Web Tools · 1회 실행 액션 스크립트\n-- XML: ${state.xmlName||'-'}\n-- Assigned image: ${state.selected}\n-- 반복/순회 제어권은 ImageMax에 있습니다. 이 파일은 호출 1회 후 즉시 반환됩니다.\n\n${rules.map(compileRule).join('\n\n')||'-- 템플릿을 선택하면 코드가 생성됩니다.'}\n`}
function hasBlockingLoop(code){return /\bwhile\s+true\b|\brepeat\b/.test(code)}
function safeLua(){const code=generatedLua();if(hasBlockingLoop(code))throw new Error('ImageMax 리스트 순회를 막는 무한/반복 대기 구조가 감지되었습니다.');return code}
function renderLua(){try{els.lua.textContent=safeLua()}catch(e){els.lua.textContent='-- 오류: '+e.message}}
els.copy.onclick=()=>{try{copyText(safeLua())}catch(e){alert(e.message)}};els.dl.onclick=()=>{try{download(`${sanitizeId(state.selected)}_web.lua`,'\ufeff'+safeLua())}catch(e){alert(e.message)}};

function normalizeRules(){for(const [name,rules] of Object.entries(state.scripts||{})){for(const r of rules||[]){if(r.kind==='conditional'&&r.condition?.type==='found'&&r.condition?.params?.image===name){r.condition={type:'current',params:{}};for(const a of r.then||[])if(a.type==='click'&&a.params?.image===name){a.type='currentClick';a.params={}}}if(r.kind==='retry'){r.missActions=r.missActions||[];r.exhaustedActions=r.exhaustedActions||[]}if(r.kind==='elapsed')r.actions=r.actions||[]}}}
function persist(){try{localStorage.setItem('imagemaxScriptProject',encodeProject({format:'imagemax-web-script',version:2,xmlName:state.xmlName,images:state.images,scripts:state.scripts,selected:state.selected}))}catch{}}
$('#saveProject').onclick=()=>download(`${sanitizeId(state.xmlName.replace(/\.xml$/i,'')||'imagemax')}.imxweb.json`,encodeProject({format:'imagemax-web-script',version:2,xmlName:state.xmlName,images:state.images,scripts:state.scripts,selected:state.selected}),'application/json');
$('#loadProject').addEventListener('change',async e=>{try{const p=await readJsonFile(e.target.files[0]);if(p.format!=='imagemax-web-script')throw new Error('ImageMax Script Builder 프로젝트가 아닙니다.');Object.assign(state,{xmlName:p.xmlName||'',images:p.images||[],scripts:p.scripts||{},selected:p.selected||null});normalizeRules();els.search.disabled=!state.images.length;renderImages();renderSelection();renderRecipes();persist();toast('프로젝트를 불러왔습니다.')}catch(err){alert(err.message)}e.target.value=''});
$('#exportAll').onclick=()=>{const entries=Object.entries(state.scripts).filter(([,r])=>r?.length);if(!entries.length)return toast('저장할 스크립트 블록이 없습니다.');const prev=state.selected,files=[],manifest={format:'imagemax-script-bundle',executionModel:'single-action-per-list-visit',xmlName:state.xmlName,generatedAt:new Date().toISOString(),assignments:[]};for(const [name] of entries){state.selected=name;const file=`${sanitizeId(name)}_web.lua`;files.push({name:`lua/${file}`,data:'\ufeff'+safeLua()});manifest.assignments.push({image:name,file})}state.selected=prev;files.push({name:'manifest.json',data:JSON.stringify(manifest,null,2)});files.push({name:'README.txt',data:'ImageMax Web Tools export\n각 Lua는 ImageMax의 스크립트 입력 액션 한 칸에서 1회 실행 후 반환됩니다.\n무한 루프는 생성하지 않습니다.\n원본 XML은 수정하지 않습니다.'});downloadBytes(`${sanitizeId(state.xmlName.replace(/\.xml$/i,'')||'imagemax')}_scripts.zip`,makeStoreZip(files),'application/zip');toast(`${entries.length}개 Lua를 ZIP으로 만들었습니다.`)};
$('#newProject').onclick=()=>{if(!confirm('현재 작업을 초기화할까요?'))return;if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);Object.assign(state,{xmlName:'',images:[],selected:null,scripts:{},imageFiles:new Map(),imageFolderStats:null,previewUrl:null});els.xml.value='';els.folder.value='';els.search.value='';els.search.disabled=true;renderFolderStatus();renderImages();renderSelection();renderRecipes();persist()};

try{const p=JSON.parse(localStorage.getItem('imagemaxScriptProject')||'null');if(p?.format==='imagemax-web-script'){Object.assign(state,{xmlName:p.xmlName||'',images:p.images||[],scripts:p.scripts||{},selected:p.selected||null});normalizeRules();els.search.disabled=!state.images.length}}catch{}
renderFolderStatus();renderImages();renderSelection();renderRecipes();
