import {$,$$,download,readJsonFile,toast,html,copyText} from '../assets/common.js';
import {validateTemplatePack} from '../script/template-library.js';
const REPO='ko9ma7/imagemax-web-tools';
const embeddedCommunity=window.IMAGEMAX_COMMUNITY_DATA||{index:{templates:[]},packs:{}};
let index=embeddedCommunity.index||{templates:[]},selectedPack=null;
const list=$('#communityList'),summary=$('#communitySummary'),search=$('#communitySearch'),submitBtn=$('#submitBtn'),preview=$('#submitPreview');
function render(){const q=search.value.trim().toLowerCase(),items=(index.templates||[]).filter(t=>`${t.title} ${t.desc||''} ${t.author||''}`.toLowerCase().includes(q));summary.textContent=`공유 템플릿 ${items.length}개`;list.innerHTML=items.map(t=>`<article class="community-card"><div class="recipe-card-top"><span class="recipe-tag">${html(t.tag||'공유')}</span><span class="recipe-cat">${html(t.author?'@'+t.author:'community')}</span></div><h3>${html(t.title)}</h3><p>${html(t.desc||'')}</p><div class="row wrap" style="margin-top:12px"><button class="btn primary small" data-use="${html(t.id)}">Script Builder에서 사용</button><button class="btn small" data-download="${html(t.id)}">JSON 저장</button></div></article>`).join('')||'<div class="template-empty"><b>아직 공개된 템플릿이 없습니다.</b><span>첫 템플릿을 공유해보세요.</span></div>';$$('[data-use]',list).forEach(b=>b.onclick=()=>useTemplate(b.dataset.use));$$('[data-download]',list).forEach(b=>b.onclick=()=>saveTemplate(b.dataset.download))}
async function load(){let source='로컬';if(location.protocol!=='file:'){try{const r=await fetch('../community/index.json',{cache:'no-store'});if(r.ok){index=await r.json();source='온라인'}}catch{}}render();summary.textContent=`공유 템플릿 ${(index.templates||[]).length}개 · ${source} 목록`}
async function getPack(id){const meta=index.templates.find(x=>x.id===id);if(!meta)throw new Error('템플릿을 찾지 못했습니다.');const embedded=embeddedCommunity.packs?.[id];if(location.protocol==='file:'&&embedded)return validateTemplatePack(structuredClone(embedded));try{const r=await fetch(`../${meta.path||`community/templates/${id}.json`}`,{cache:'no-store'});if(r.ok)return validateTemplatePack(await r.json())}catch{}if(embedded)return validateTemplatePack(structuredClone(embedded));throw new Error('템플릿 파일을 읽지 못했습니다.')}
async function useTemplate(id){try{const pack=await getPack(id),raw=JSON.stringify(pack);localStorage.setItem('imagemaxPendingTemplateImport',raw);const encoded=encodeURIComponent(raw);location.href=encoded.length<100000?`../script/#importTemplate=${encoded}`:'../script/'}catch(e){alert(e.message)}}
async function saveTemplate(id){try{const pack=await getPack(id);const t=pack.templates[0];download(`${(t.title||id).replace(/[\\/:*?"<>|]/g,'_')}.imxtpl.json`,JSON.stringify(pack,null,2),'application/json')}catch(e){alert(e.message)}}
function bodyFor(pack){return `<!-- IMAGEMAX_TEMPLATE_SUBMISSION -->\nImageMax Web Tools에서 제출한 공유 템플릿입니다.\n\n<!-- IMAGEMAX_TEMPLATE_JSON_START -->\n\`\`\`json\n${JSON.stringify(pack,null,2)}\n\`\`\`\n<!-- IMAGEMAX_TEMPLATE_JSON_END -->\n`}
async function directSubmissionBody(pack){const provider=window.IMAGEMAX_GET_TURNSTILE_TOKEN,turnstileToken=typeof provider==='function'?await provider():window.IMAGEMAX_TURNSTILE_TOKEN;if(!turnstileToken)throw new Error('직접 제출 모드에 Cloudflare Turnstile 토큰 공급자가 설정되지 않았습니다. 기본 GitHub Issue 모드를 사용하거나 공유 설정을 확인하세요.');return {pack,turnstileToken}}
async function submit(){if(!selectedPack)return;const endpoint=window.IMAGEMAX_SHARE_ENDPOINT||'';try{validateTemplatePack(selectedPack,{maxTemplates:20,maxPackBytes:60000});if(endpoint){const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(await directSubmissionBody(selectedPack))}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`공유 API 오류 ${r.status}`);toast('공유 신청이 접수되었습니다.');if(d.url)open(d.url,'_blank','noopener');return}const body=bodyFor(selectedPack);if(body.length>50000)throw new Error('GitHub Issue 제출 방식의 안전 크기를 넘었습니다. 템플릿을 나누어 제출하거나 서버리스 직접 모드를 설정하세요.');const title=`[Template] ${selectedPack.templates[0]?.title||selectedPack.name||'ImageMax template'}`,encoded=encodeURIComponent(body);if(encoded.length<=6000){open(`https://github.com/${REPO}/issues/new?title=${encodeURIComponent(title)}&body=${encoded}`,'_blank','noopener');toast('GitHub 제출 화면을 열었습니다. Issue를 등록하면 자동 검증이 시작됩니다.');return}await copyText(body);open(`https://github.com/${REPO}/issues/new?title=${encodeURIComponent(title)}`,'_blank','noopener');alert('템플릿 본문이 길어 클립보드에 복사했습니다. 열린 Issue 본문에 붙여넣고 등록하세요.')}catch(e){alert(e.message)}}
$('#submitFile').addEventListener('change',async e=>{try{selectedPack=validateTemplatePack(await readJsonFile(e.target.files[0]));const n=selectedPack.templates.length,size=new Blob([JSON.stringify(selectedPack)]).size;preview.innerHTML=`<b>${html(selectedPack.name||'Template Pack')}</b><br>${n}개 템플릿 · ${(size/1024).toFixed(1)} KB · 형식 검사 정상`;submitBtn.disabled=false}catch(err){selectedPack=null;submitBtn.disabled=true;preview.textContent='오류: '+err.message}e.target.value=''});submitBtn.onclick=submit;search.oninput=render;$('#refreshCommunity').onclick=load;if(window.IMAGEMAX_SHARE_ENDPOINT)$('#directModeText').textContent='서버리스 직접 제출 모드가 설정되어 있습니다. 페이지에서 제출하면 중계 API가 GitHub Issue를 생성하고 Action이 이어서 검증합니다.';load();
